### ISSUE TITLE
Resolve crash when a run is ended.

### ISSUE THREAD

**Issue by mattloose** [LooseLab/readfish#109]
Automatic termination of a run will lead to an error in readfish as we expect the run to exist.

```
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/home/grid/GIT/readfish_release_test/readfish/lib/python3.5/site-packages/ru/run_until_utils.py", line 263, in processfiles
    self.connection.protocol.stop_protocol()
  File "/home/grid/GIT/readfish_release_test/readfish/lib/python3.5/site-packages/minknow_api/protocol_service.py", line 122, in stop_protocol
    return run_with_retry(self._stub.stop_protocol, _message, _timeout, [], "minknow_api.protocol.ProtocolService")
  File "/home/grid/GIT/readfish_release_test/readfish/lib/python3.5/site-packages/minknow_api/protocol_service.py", line 56, in run_with_retry
    result = MessageWrapper(method(message, timeout=timeout), unwraps=unwraps)
  File "/home/grid/GIT/readfish_release_test/readfish/lib/python3.5/site-packages/grpc/_channel.py", line 826, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/home/grid/GIT/readfish_release_test/readfish/lib/python3.5/site-packages/grpc/_channel.py", line 729, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.FAILED_PRECONDITION
        details = "Script not running"
        debug_error_string = "{"created":"@1603887831.706851950","description":"Error received from peer ipv4:127.0.0.1:8004","file":"src/core/lib/surface/call.cc","file_line":1061,"grpc_message":"Script not running","grpc_status":9}"
>

checking references
{'test'}
test
This reference is OK.
```

**Comment by 12032345** [comment]
Hi matt,

I had a similar problem as follow screenshot when I run readfish targets, and at that time my sequencing run was not terminated. So what's going on ? How can I solve this problem?

![Screenshot from 2020-12-1602-59-40](https://user-images.githubusercontent.com/70840449/102303441-1f6fd880-3f96-11eb-8bd6-bdb88e12e0a0.png)

sophie

**Comment by mattloose** [comment]
So the error is telling you that at the point you were trying to connect there was no run actually active on the device. This can be because you have started readfish before the run started or you are pointing at the wrong position on a gridion.
