### ISSUE TITLE
readfish not rejecting reads but appears to be running

### ISSUE THREAD

**Issue by danrdanny** [LooseLab/readfish#125]
Hi all, setting myself up here for a potentially dumb question. We recently upgraded MinKNOW to v4 and I am getting  inconsistent results with readfish. I'll start with the basics.

Running 4.0.11 as the basecall server:
`/home/grid/ont-guppy_4.0.11/bin/guppy_basecall_server --config /home/grid/ont-guppy_4.0.11/data/dna_r9.4.1_450bps_fast.cfg --log_path /home/grid/readUntilProject/guppyBasecallServer/ --port 5556 --device "cuda:all"`

Running readfish as such:
`readfish targets --experiment-name "sample-ONT-RU-01" --device X1 --toml /home/grid/readUntilProject/toml.sample-ONT-RU-01 --log-file /data/ru_log/log.ru.sample`

toml file:

[caller_settings]
config_name = "dna_r9.4.1_450bps_fast"
host = "127.0.0.1"
port = 5556

[conditions]
reference = "/home/grid/readUntilProject/hg38.mmi"

[conditions.0]
name = "sample-ONT-RU-01"
control = false
min_chunks = 0
max_chunks = 12
targets = "/home/grid/readUntilProject/targetFiles/targets.sample-ONT-RU-01"
single_on = "stop_receiving"
multi_on = "stop_receiving"
single_off = "unblock"
multi_off = "unblock"
no_seq = "proceed"
no_map = "proceed"

target file:

chr2,196000000,200000000,+
chr19,28000000,32000000,+
chr2,196000000,200000000,-
chr19,28000000,32000000,-

When I run this, I see readfish start as expected and it begins sampling reads:

readfish targets --experiment-name "sample-ONT-RU-01" --device X1 --toml /home/grid/readUntilProject/toml.sample-ONT-RU-01 --log-file /data/ru_log/log.ru.sample
2021-01-13 11:22:08,130 ru.ru_gen /home/grid/readfish/bin/readfish targets --experiment-name sample-ONT-RU-01 --device X1 --toml /home/grid/readUntilProject/toml.sample-ONT-RU-01 --log-file /data/ru_log/log.ru.sample
2021-01-13 11:22:08,130 ru.ru_gen action_throttle=0.001
2021-01-13 11:22:08,131 ru.ru_gen batch_size=512
2021-01-13 11:22:08,131 ru.ru_gen cache_size=512
2021-01-13 11:22:08,131 ru.ru_gen channels=[1, 512]
2021-01-13 11:22:08,131 ru.ru_gen chunk_log=None
2021-01-13 11:22:08,131 ru.ru_gen command=targets
2021-01-13 11:22:08,131 ru.ru_gen device=X3
2021-01-13 11:22:08,131 ru.ru_gen dry_run=False
2021-01-13 11:22:08,131 ru.ru_gen experiment_name=sample-ONT-RU-01
2021-01-13 11:22:08,131 ru.ru_gen func=<function run at 0x7f6cdd26b378>
2021-01-13 11:22:08,131 ru.ru_gen host=127.0.0.1
2021-01-13 11:22:08,131 ru.ru_gen log_file=/data/ru_log/log.ru.sample
2021-01-13 11:22:08,131 ru.ru_gen log_format=%(asctime)s %(name)s %(message)s
2021-01-13 11:22:08,131 ru.ru_gen log_level=info
2021-01-13 11:22:08,131 ru.ru_gen paf_log=None
2021-01-13 11:22:08,131 ru.ru_gen port=9501
2021-01-13 11:22:08,131 ru.ru_gen run_time=172800
2021-01-13 11:22:08,131 ru.ru_gen throttle=0.1
2021-01-13 11:22:08,131 ru.ru_gen toml=/home/grid/readUntilProject/toml.sample-ONT-RU-01
2021-01-13 11:22:08,131 ru.ru_gen unblock_duration=0.1
2021-01-13 11:22:08,131 ru.ru_gen workers=1
2021-01-13 11:22:08,137 ru.ru_gen Initialising minimap2 mapper
2021-01-13 11:22:14,966 ru.ru_gen Mapper initialised
Using pre-defined read classification map.
2021-01-13 11:22:14,975 ru.ru_gen This experiment has 1 region on the flowcell
2021-01-13 11:22:14,975 ru.ru_gen Using reference: /home/grid/readUntilProject/hg38.mmi
2021-01-13 11:22:14,976 ru.ru_gen Region 'sample-ONT-RU-01' (control=False) has 2 targets of which 2 are in the reference. Reads will be unblocked when classed as single_off or multi_off; sequenced when classed as single_on or multi_on; and polled for more data when classed as no_map or no_seq.

After starting I get the message in MinKNOW that readfish is controlling the run, etc. But, reads are not rejected. It just proceeds as if no selection is occurring.

What is driving me crazy is that this is working fine for mouse samples. I have changed ports (X3->X1, for example) and the problem persists. The only difference in the configs I pasted above when running a mouse sample is that I'm using mm10.mmi instead of hg38.mmi. When I run a mouse sample I see a peak of reads <1kb as expected. I have yet to run a successful readfish or adaptive sampling run on a human sample using MinKNOW 4. 

Here's hoping this is something simple I'm missing and this becomes eternal evidence that I made a silly config error. Let me know if any additional config information will be helpful.

**Comment by alexomics** [comment]
If this is working with a `mm10.mmi` but not `hg38.mmi` I would start by regenerating the human reference MMI.

If that doesn't work, I would then regenerate the readfish env as outlined here: https://github.com/LooseLab/readfish/issues/124#issuecomment-759599319

**Comment by danrdanny** [comment]
Thanks @alexomics, I didn't mention but I did try making a new hg38.mmi before trying and that didn't work. I did just try getting a new hg38.fa from UCSC and made a new hg38.mmi. Same result. So, I reinstalled based on comment #124. It validated my toml with no changes to the toml, but now gives me the following error when starting an experiment. Also, I changed my basecall server from guppy 4.0.11 to the default 4.2.3.

This is true for both my mouse and human runs: 

$ readfish targets --experiment-name "sample-ONT-RU-01" --device X1 --toml /home/grid/readUntilProject/toml.sample-ONT-RU-01 --log-file /data/ru_log/log.ru.sample
2021-01-13 15:13:21,387 ru.ru_gen /data/.miniconda/envs/readfish/bin/readfish targets --experiment-name sample-ONT-RU-01 --device X1 --toml /home/grid/readUntilProject/toml.sample-ONT-RU-01 --log-file /data/ru_log/log.ru.sample
2021-01-13 15:13:21,387 ru.ru_gen batch_size=512
2021-01-13 15:13:21,387 ru.ru_gen cache_size=512
2021-01-13 15:13:21,387 ru.ru_gen channels=[1, 512]
2021-01-13 15:13:21,387 ru.ru_gen chunk_log=None
2021-01-13 15:13:21,387 ru.ru_gen command=targets
2021-01-13 15:13:21,387 ru.ru_gen device=X1
2021-01-13 15:13:21,387 ru.ru_gen dry_run=False
2021-01-13 15:13:21,387 ru.ru_gen experiment_name=sample-ONT-RU-01
2021-01-13 15:13:21,387 ru.ru_gen func=<function run at 0x7f6876f75e60>
2021-01-13 15:13:21,387 ru.ru_gen host=127.0.0.1
2021-01-13 15:13:21,387 ru.ru_gen log_file=/data/ru_log/log.ru.S087
2021-01-13 15:13:21,387 ru.ru_gen log_format=%(asctime)s %(name)s %(message)s
2021-01-13 15:13:21,387 ru.ru_gen log_level=info
2021-01-13 15:13:21,387 ru.ru_gen paf_log=None
2021-01-13 15:13:21,387 ru.ru_gen port=9501
2021-01-13 15:13:21,387 ru.ru_gen run_time=172800
2021-01-13 15:13:21,387 ru.ru_gen throttle=0.4
2021-01-13 15:13:21,387 ru.ru_gen toml=/home/grid/readUntilProject/toml.sample-ONT-RU-01
2021-01-13 15:13:21,387 ru.ru_gen unblock_duration=0.1
2021-01-13 15:13:21,387 ru.ru_gen workers=1
2021-01-13 15:13:21,390 ru.ru_gen Initialising minimap2 mapper
2021-01-13 15:13:27,609 ru.ru_gen Mapper initialised
2021-01-13 15:13:27,615 ru.ru_gen This experiment has 1 region on the flowcell
2021-01-13 15:13:27,615 ru.ru_gen Using reference: /home/grid/readUntilProject/hg38.mmi
2021-01-13 15:13:36,065 ru.ru_gen Region 'sample-ONT-RU-01' (control=False) has 2 contigs of which 2 are in the reference. There are 4 targets (including +/- strand) representing 0.25% of the reference. Reads will be unblocked when classed as single_off or multi_off; sequenced when classed as single_on or multi_on; and polled for more data when classed as no_map or no_seq.
[2021-01-13 15:13:36.084829] [0x00007f68a4422700] [info]    Connecting to server as
Traceback (most recent call last):
  File "/data/.miniconda/envs/readfish/bin/readfish", line 8, in <module>
    sys.exit(main())
  File "/data/.miniconda/envs/readfish/lib/python3.7/site-packages/ru/cli.py", line 42, in main
    args.func(parser, args)
  File "/data/.miniconda/envs/readfish/lib/python3.7/site-packages/ru/ru_gen.py", line 510, in run
    caller_kwargs=caller_kwargs,
  File "/data/.miniconda/envs/readfish/lib/python3.7/site-packages/ru/ru_gen.py", line 157, in simple_analysis
    config=caller_kwargs["config_name"],
  File "/data/.miniconda/envs/readfish/lib/python3.7/site-packages/ru/basecall.py", line 39, in __init__
    self.connect()
  File "/data/.miniconda/envs/readfish/lib/python3.7/site-packages/pyguppy_client_lib/pyclient.py", line 140, in connect
    raise ValueError("Basecalling config unavailable: {!r}".format(return_code))
ValueError: Basecalling config unavailable: result.basecall_config_unavailable

Also, I didn't mention it before but MinKNOW version is 4.1.22.

**Comment by danrdanny** [comment]
Okay, so just made some progress by actually looking at the code. It seems like I don't need a separate basecall server running now, I can just use the default one on port 5555? By stopping the separate one I had and pointing my toml at 5555 both my human and mouse experiments are running and selecting reads. 

The only problem now is that the selection is taking too long, so I'm getting a peak at ~2kb with times of 0.15 to 0.25. I'll work on this now with some settings.

**Comment by alexomics** [comment]
This looks like an issue with the guppy configuration. Can you post the output of:

```bash
ls -gtrh /opt/ont/guppy/data/dna_r9*
```

**Comment by danrdanny** [comment]
@alexomics, here's the output of the guppy config folder:

$ ls -gtrh /opt/ont/guppy/data/dna_r9*
-rw-r--r-- 1 root 1.6K Aug 19 01:04 /opt/ont/guppy/data/dna_r9.5_450bps.cfg
-rw-r--r-- 1 root 1.1K Oct 12 00:34 /opt/ont/guppy/data/dna_r9.4.1_450bps_modbases_dam-dcm-cpg_hac_prom.cfg
-rw-r--r-- 1 root 1.1K Oct 12 00:34 /opt/ont/guppy/data/dna_r9.4.1_450bps_modbases_dam-dcm-cpg_hac.cfg
-rw-r--r-- 1 root 1.1K Oct 12 00:34 /opt/ont/guppy/data/dna_r9.4.1_450bps_hac_prom_fw205.cfg
-rw-r--r-- 1 root 1.3K Oct 12 00:34 /opt/ont/guppy/data/dna_r9.4.1_450bps_fast_prom.cfg
-rw-r--r-- 1 root 1.2K Oct 12 00:34 /opt/ont/guppy/data/dna_r9.4.1_450bps_fast.cfg
-rw-r--r-- 1 root 1.6K Oct 13 14:00 /opt/ont/guppy/data/dna_r9.4.1_450bps_hac_prom.cfg
-rw-r--r-- 1 root 1.8K Oct 13 14:00 /opt/ont/guppy/data/dna_r9.4.1_450bps_hac.cfg
