### ISSUE TITLE
undefined return code: result.bad_request

### ISSUE THREAD

**Issue by tanaes** [LooseLab/readfish#144]
Try to get mapping enrichment working, and I'm wondering if the following issue has to do with API version mismatch?

Because I'm trying toget things to work on an Ampere GPU under the current release of MinKNOW, I'm stuck with the patched version 4.3.4 of Guppy. However, there is no corresponding version in the [PyPi repository for ont-pyguppy-client-lib](https://pypi.org/project/ont-pyguppy-client-lib/#history). I tried installing the next version (4.4.0). 

readfish is opening fine, and I can get it to unblock all, but when I try to unblock based on a reference I get the following error:

```
(readfish) moellerlab@moeller-lab-lambda:~/Desktop/read-until/readfish-test/test-data$ readfish targets --device MN25321 \
>               --experiment-name "readfish-test" \
>               --toml /home/moellerlab/Desktop/read-until/readfish-test/test-data/human_chr_selection.toml \
>               --log-file ru_test.log
2021-04-06 16:48:28,479 ru.ru_gen /home/moellerlab/software/readfish/bin/readfish targets --device MN25321 --experiment-name readfish-test --toml /home/moellerlab/Desktop/read-until/readfish-test/test-data/human_chr_selection.toml --log-file ru_test.log
2021-04-06 16:48:28,479 ru.ru_gen batch_size=512
2021-04-06 16:48:28,479 ru.ru_gen cache_size=512
2021-04-06 16:48:28,479 ru.ru_gen channels=[1, 512]
2021-04-06 16:48:28,479 ru.ru_gen chunk_log=None
2021-04-06 16:48:28,479 ru.ru_gen command=targets
2021-04-06 16:48:28,480 ru.ru_gen device=MN25321
2021-04-06 16:48:28,480 ru.ru_gen dry_run=False
2021-04-06 16:48:28,480 ru.ru_gen experiment_name=readfish-test
2021-04-06 16:48:28,480 ru.ru_gen func=<function run at 0x7f408efc4dc0>
2021-04-06 16:48:28,480 ru.ru_gen host=127.0.0.1
2021-04-06 16:48:28,480 ru.ru_gen log_file=ru_test.log
2021-04-06 16:48:28,480 ru.ru_gen log_format=%(asctime)s %(name)s %(message)s
2021-04-06 16:48:28,480 ru.ru_gen log_level=info
2021-04-06 16:48:28,480 ru.ru_gen paf_log=None
2021-04-06 16:48:28,480 ru.ru_gen port=9501
2021-04-06 16:48:28,480 ru.ru_gen run_time=172800
2021-04-06 16:48:28,480 ru.ru_gen throttle=0.4
2021-04-06 16:48:28,480 ru.ru_gen toml=/home/moellerlab/Desktop/read-until/readfish-test/test-data/human_chr_selection.toml
2021-04-06 16:48:28,480 ru.ru_gen unblock_duration=0.1
2021-04-06 16:48:28,480 ru.ru_gen workers=1
2021-04-06 16:48:28,483 ru.ru_gen Initialising minimap2 mapper
2021-04-06 16:48:33,671 ru.ru_gen Mapper initialised
2021-04-06 16:48:33,680 ru.ru_gen This experiment has 1 region on the flowcell
2021-04-06 16:48:33,680 ru.ru_gen Using reference: /home/moellerlab/Desktop/read-until/readfish-test/test-data/GRCh38_genomic.mmi
2021-04-06 16:48:41,960 ru.ru_gen Region 'select_chr_6_7' (control=False) has 2 contigs of which 2 are in the reference. There are 4 targets (including +/- strand) representing 10.29% of the reference. Reads will be unblocked when classed as single_off or multi_off; sequenced when classed as single_on or multi_on; and polled for more data when classed as no_map or no_seq.
Traceback (most recent call last):
  File "/home/moellerlab/software/readfish/bin/readfish", line 11, in <module>
    load_entry_point('readfish==0.0.6', 'console_scripts', 'readfish')()
  File "/home/moellerlab/software/readfish/lib/python3.8/site-packages/ru/cli.py", line 42, in main
    args.func(parser, args)
  File "/home/moellerlab/software/readfish/lib/python3.8/site-packages/ru/ru_gen.py", line 498, in run
    simple_analysis(
  File "/home/moellerlab/software/readfish/lib/python3.8/site-packages/ru/ru_gen.py", line 155, in simple_analysis
    caller = Caller(
  File "/home/moellerlab/software/readfish/lib/python3.8/site-packages/ru/basecall.py", line 41, in __init__
    self.connect()
  File "/home/moellerlab/software/readfish/lib/python3.8/site-packages/pyguppy_client_lib/pyclient.py", line 174, in connect
    raise RuntimeError("Undefined return code: {}".format(return_code))
RuntimeError: Undefined return code: result.bad_request
```

**Comment by alexomics** [comment]
It seems that the guppy client can’t connect to the server, can you share the `caller_settings` table from your config toml? And check what port the `guppy_basecall_server` is running on.

We may need to try a stand-alone server, but we should check these first.

**Comment by tanaes** [comment]
Looks like Guppy is running on default:

```
(readfish) moellerlab@moeller-lab-lambda:~/Desktop/read-until/readfish-test$ sudo lsof -i | grep guppy
guppy_bas  88373            root   12u  IPv4  556607      0t0  TCP *:5555 (LISTEN)
guppy_bas  88373            root   45u  IPv4 9383019      0t0  TCP localhost:5555->localhost:45254 (ESTABLISHED)
```

Here's my `caller_settings`:

```
[caller_settings]
config_name = "dna_r9.4.1_450bps_fast"
host = "127.0.0.1"
port = 5555
```

Thanks for the help!

**Comment by tanaes** [comment]
...maybe a stupid question, but I should have basecalling turned on in MinKNOW using the same model as in the TOML file, right?

**Comment by alexomics** [comment]
You don’t need to be base calling with minknow at the same time. I don’t think it needs to be that same model. 

Your caller settings look fine, I think this is a guppy server that there isn’t a corresponding client for.

let me run a couple of tests and I’ll get back to you

**Comment by tanaes** [comment]
Aha. Yup, that clarified things! I set up a standalone Guppy server using 4.5.2, installed the corresponding client via pip, and set it running on 5556. It is working now with using the bulk data simulation!

**Comment by alexomics** [comment]
Thanks for the update, I'll check with ONT to see if there is a client available

**Comment by bhargava-morampalli** [comment]
@tanaes 
Can you please let me know how you resolved this issue in a little bit detail? I have the same problem and I do not know how to "set up a standalone Guppy server using 4.5.2, installed the corresponding client via pip, and set it running on 5556."

**Comment by tanaes** [comment]
Sure! Briefly, I followed the standard Guppy install directions for
installing from a tar ball. I downloaded the 4.5.2 Guppy linux tarball
from the nanopore site, then unzipped it to its own folder in my home
directory. During the portion of the ReadFish installation instructions
that calls for installing the guppy client via pip, I just specified the
4.5.2 version. Finally, when I wanted to run the adaptive sampling, I
started this version of the guppy_basecaller_server with the --port 5556
flag so that it started on a different port from MinKnow's guppy
server. 

Hope that helps! I can write back with more specific detail in a couple
days once I'm back in the lab.

On April 13, 2021, Github Notifications ***@***.***>
wrote:
> @tanaes <https://github.com/tanaes>
>  Can you please let me know how you resolved this issue in a little
> bit detail? I have the same problem and I do not know how to "set up a
> standalone Guppy server using 4.5.2, installed the corresponding
> client via pip, and set it running on 5556."
>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/LooseLab/readfish/issues/144#issuecomment-
819220695>, or unsubscribe
<https://github.com/notifications/unsubscribe-
auth/AB7ISADQ3PIDZ5DDCMM76C3TIULMZANCNFSM42PPIKFA>.

**Comment by haqueb2** [comment]
> Sure! Briefly, I followed the standard Guppy install directions for installing from a tar ball. I downloaded the 4.5.2 Guppy linux tarball from the nanopore site, then unzipped it to its own folder in my home directory. During the portion of the ReadFish installation instructions that calls for installing the guppy client via pip, I just specified the 4.5.2 version. Finally, when I wanted to run the adaptive sampling, I started this version of the guppy_basecaller_server with the --port 5556 flag so that it started on a different port from MinKnow's guppy server.  Hope that helps! I can write back with more specific detail in a couple days once I'm back in the lab.
> On April 13, 2021, Github Notifications ***@***.***> wrote: @tanaes <https://github.com/tanaes> Can you please let me know how you resolved this issue in a little bit detail? I have the same problem and I do not know how to "set up a standalone Guppy server using 4.5.2, installed the corresponding client via pip, and set it running on 5556."
> — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub <[#144 (comment)](https://github.com/LooseLab/readfish/issues/144#issuecomment)- 819220695>, or unsubscribe <https://github.com/notifications/unsubscribe- auth/AB7ISADQ3PIDZ5DDCMM76C3TIULMZANCNFSM42PPIKFA>.

@tanaes I've been having the same error message you previously had. I followed your instructions, however I still seem to be getting the "result.bad_request" message. After you unzipped the 4.5.2 Guppy linux tarball file, did you save the folder it in a specific folder within ReadFish?
