### ISSUE TITLE
encountered permission denied

### ISSUE THREAD

**Issue by fayweili** [LooseLab/readfish#153]
Hi, I was able to install readfish using conda, but when I tried to follow the testing steps to unblock simulated run, I got:

```
INFO 2021-06-22 15:41:20,704 Manager /home/lilab/miniconda3/envs/readfish/bin/readfish unblock-all --device MN28490 --experiment-name test2
2021-06-22 15:41:20,704 Manager /home/lilab/miniconda3/envs/readfish/bin/readfish unblock-all --device MN28490 --experiment-name test2
INFO 2021-06-22 15:41:20,705 Manager batch_size=512
2021-06-22 15:41:20,705 Manager batch_size=512
INFO 2021-06-22 15:41:20,705 Manager cache_size=512
2021-06-22 15:41:20,705 Manager cache_size=512
INFO 2021-06-22 15:41:20,705 Manager channels=[1, 512]
2021-06-22 15:41:20,705 Manager channels=[1, 512]
INFO 2021-06-22 15:41:20,705 Manager command=unblock-all
2021-06-22 15:41:20,705 Manager command=unblock-all
INFO 2021-06-22 15:41:20,705 Manager device=MN28490
2021-06-22 15:41:20,705 Manager device=MN28490
INFO 2021-06-22 15:41:20,705 Manager dry_run=False
2021-06-22 15:41:20,705 Manager dry_run=False
INFO 2021-06-22 15:41:20,705 Manager experiment_name=test2
2021-06-22 15:41:20,705 Manager experiment_name=test2
INFO 2021-06-22 15:41:20,705 Manager func=<function run at 0x7f3f0263b4d0>
2021-06-22 15:41:20,705 Manager func=<function run at 0x7f3f0263b4d0>
INFO 2021-06-22 15:41:20,705 Manager host=127.0.0.1
2021-06-22 15:41:20,705 Manager host=127.0.0.1
INFO 2021-06-22 15:41:20,705 Manager log_file=None
2021-06-22 15:41:20,705 Manager log_file=None
INFO 2021-06-22 15:41:20,705 Manager log_format=%(asctime)s %(name)s %(message)s
2021-06-22 15:41:20,705 Manager log_format=%(asctime)s %(name)s %(message)s
INFO 2021-06-22 15:41:20,705 Manager log_level=info
2021-06-22 15:41:20,705 Manager log_level=info
INFO 2021-06-22 15:41:20,705 Manager port=9501
2021-06-22 15:41:20,705 Manager port=9501
INFO 2021-06-22 15:41:20,705 Manager run_time=172800
2021-06-22 15:41:20,705 Manager run_time=172800
INFO 2021-06-22 15:41:20,705 Manager throttle=0.4
2021-06-22 15:41:20,705 Manager throttle=0.4
INFO 2021-06-22 15:41:20,705 Manager unblock_duration=0.1
2021-06-22 15:41:20,705 Manager unblock_duration=0.1
INFO 2021-06-22 15:41:20,705 Manager workers=1
2021-06-22 15:41:20,705 Manager workers=1
INFO 2021-06-22 15:41:20,763 ReadUntil Got rpc connection.
2021-06-22 15:41:20,763 ReadUntil Got rpc connection.
INFO 2021-06-22 15:41:20,807 ReadUntil Creating single chunk client with AccumulatingCache data queue filtering to strand and adapter read chunks.
2021-06-22 15:41:20,807 ReadUntil Creating single chunk client with AccumulatingCache data queue filtering to strand and adapter read chunks.
DEBUG 2021-06-22 15:41:20,807 ReadUntil Strand-like classes are {65, 83}.
Traceback (most recent call last):
  File "/home/lilab/miniconda3/envs/readfish/bin/readfish", line 8, in <module>
    sys.exit(main())
  File "/home/lilab/miniconda3/envs/readfish/lib/python3.7/site-packages/ru/cli.py", line 42, in main
    args.func(parser, args)
  File "/home/lilab/miniconda3/envs/readfish/lib/python3.7/site-packages/ru/unblock_all.py", line 133, in run
    cache_type=AccumulatingCache,
  File "/home/lilab/miniconda3/envs/readfish/lib/python3.7/site-packages/ru/read_until_client.py", line 43, in __init__
    str(Path(self.mk_run_dir).joinpath("unblocked_read_ids.txt"))
  File "/home/lilab/miniconda3/envs/readfish/lib/python3.7/logging/__init__.py", line 1087, in __init__
    StreamHandler.__init__(self, self._open())
  File "/home/lilab/miniconda3/envs/readfish/lib/python3.7/logging/__init__.py", line 1116, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
PermissionError: [Errno 13] Permission denied: '/var/lib/minknow/data/test/test/20210622_1525_MN28490_test_131de983/unblocked_read_ids.txt'

```

Any help would be fantastic. Thank you!!

**Comment by mattloose** [comment]
Could you confirm what version of MinKNOW you are running please?

Thanks!

**Comment by fayweili** [comment]
21.06.2

**Comment by mattloose** [comment]
OK - so there are a couple of possibilities here. It looks as though the folder that is being created by MinKNOW for the run doesn't have the necessary permissions for the user that is running readfish. This could be caused by your local set up or we have seen - in the past - issues with MinKNOW creating folders with incorrect permissions. I'll page @alexomics and see if he has any suggestions here...

**Comment by alexomics** [comment]
Yep, this is most likely a problem with the directory permissions. I've pushed a small change to [issue153](/LooseLab/readfish/tree/issue153) which you can install using conda by setting the `readfish` dependency to:

```yaml
  - pip:
    - git+https://github.com/LooseLab/readfish@issue153
```

If you could test that out and let me know if it works that'd be great.

**Comment by fayweili** [comment]
I made a fresh conda install with the modified yml file, but got the same permission denied message. 

Thanks for helping out!!

**Comment by alexomics** [comment]
Okay, could you run:

```bash
stat /var/lib/minknow/data/test/test/20210622_1525_MN28490_test_131de983
```
and post the result here?

**Comment by fayweili** [comment]
```
(readfish_06232021S) lilab@lilab:~/Downloads$ ls -l /var/lib/minknow/data/test/test/
drwxrwxr-x 8 minknow minknow 4096 Jun 22 15:24 20210622_1455_MN28490_test_a32bed21
drwxrwxr-x 7 minknow minknow 4096 Jun 22 18:00 20210622_1525_MN28490_test_131de983
drwxrwxr-x 7 minknow minknow 4096 Jun 23 09:24 20210623_0924_MN28490_test_93fe74bc
```

```
(readfish_06232021S) lilab@lilab:~/Downloads$ stat /var/lib/minknow/data/test/test/
  File: /var/lib/minknow/data/test/test/
  Size: 4096      	Blocks: 8          IO Block: 4096   directory
Device: 10302h/66306d	Inode: 4849720     Links: 5
Access: (0775/drwxrwxr-x)  Uid: (  998/ minknow)   Gid: (  998/ minknow)
Access: 2021-06-23 09:44:51.022120950 -0400
Modify: 2021-06-23 09:24:08.283782960 -0400
Change: 2021-06-23 09:24:08.283782960 -0400
 Birth: -
```

**Comment by alexomics** [comment]
The folder is owned by `minknow`, if you have administrator permissions on this computer you can add yourself to that group by running:

```bash
sudo usermod -a -G lilab minknow
```

I'm also going to push another patch that will change where the unblocked read ids are written if we see a `PermissionError`

**Comment by fayweili** [comment]
sorry I must have missed something. I tried the usermod command, but still got the same error.

**Comment by alexomics** [comment]
I forgot to mention that if you add your user to the minknow group you may need to logout and back in for the changes to take effect.

Sorry 😅

**Comment by fayweili** [comment]
ummm I logged out and back in. But still there...

**Comment by fayweili** [comment]
```
(readfish_06232021S) lilab@lilab:~$ groups
lilab adm cdrom sudo dip plugdev lpadmin sambashare
```

**Comment by alexomics** [comment]
Okay, you're not in the minknow group, I put the group and user the wrong way, sorry

```bash
sudo usermod -a -G minknow lilab
```

**Comment by fayweili** [comment]
lol still not working. tried the new usermod line, logged out and back, and still denied.

**Comment by alexomics** [comment]
Okay. Can you update to the latest `issue153` code by removing/recreating the conda environment, run:

```bash
readfish --version
```

and then try the test and post the version and error here?

**Comment by fayweili** [comment]
ohhhhhhhhh!!!!! IT'S WORKING NOW!!!!!!!!

**Comment by alexomics** [comment]
Fantastic! Is this using `v0.0.6dev2`?

**Comment by fayweili** [comment]
yes

**Comment by alexomics** [comment]
Okay, in this version if we can't use the minknow output directory the `unblocked_read_ids.txt` is output into the working directory. I'll do some more testing with this and merge it into the main branches soon. Thanks for bringing this to our attention!

**Comment by YingziZhang-github** [comment]
Hi there,
Same problem here. `Permission denied: '/nanopore/minknow/data/YZ_Test/YZ_Test_1/20210803_1337_MN32433_FAP69493_6d55011e/unblocked_read_ids.txt'` 
I am not sure what parameters I need to set here. Would you please help? Information is here. Thank you in advance.
```
(readfish) (base) zhany0s@kw60889:~/Yingzi_software$ ls -l /nanopore/minknow/data/YZ_Test/YZ_Test_1/
total 12
drwxrwxr-x 8 minknow minknow 4096 Aug  1 22:59 20210801_2216_MN32433_FAP69493_0d37ddb0
drwxrwxr-x 8 minknow minknow 4096 Aug  1 23:38 20210801_2322_MN32433_FAP69493_8b206807
drwxrwxr-x 7 minknow minknow 4096 Aug  3 13:37 20210803_1337_MN32433_FAP69493_6d55011e
(readfish) (base) zhany0s@kw60889:~/Yingzi_software$ stat /nanopore/minknow/data/YZ_Test/YZ_Test_1/
  File: /nanopore/minknow/data/YZ_Test/YZ_Test_1/
  Size: 4096      	Blocks: 8          IO Block: 4096   directory
Device: 811h/2065d	Inode: 177602572   Links: 5
Access: (0775/drwxrwxr-x)  Uid: (  999/ minknow)   Gid: (  998/ minknow)
Access: 2021-08-03 13:47:16.357777677 +0300
Modify: 2021-08-03 13:37:31.387586246 +0300
Change: 2021-08-03 13:37:31.387586246 +0300
 Birth: -
(readfish) (base) zhany0s@kw60889:~/Yingzi_software$ groups
g-zhany0s sudo noor-users rc-stemcellrlab
```

**Comment by YingziZhang-github** [comment]
> Hi there,
> Same problem here. `Permission denied: '/nanopore/minknow/data/YZ_Test/YZ_Test_1/20210803_1337_MN32433_FAP69493_6d55011e/unblocked_read_ids.txt'`
> I am not sure what parameters I need to set here. Would you please help? Information is here. Thank you in advance.
> 
> ```
> (readfish) (base) zhany0s@kw60889:~/Yingzi_software$ ls -l /nanopore/minknow/data/YZ_Test/YZ_Test_1/
> total 12
> drwxrwxr-x 8 minknow minknow 4096 Aug  1 22:59 20210801_2216_MN32433_FAP69493_0d37ddb0
> drwxrwxr-x 8 minknow minknow 4096 Aug  1 23:38 20210801_2322_MN32433_FAP69493_8b206807
> drwxrwxr-x 7 minknow minknow 4096 Aug  3 13:37 20210803_1337_MN32433_FAP69493_6d55011e
> (readfish) (base) zhany0s@kw60889:~/Yingzi_software$ stat /nanopore/minknow/data/YZ_Test/YZ_Test_1/
>   File: /nanopore/minknow/data/YZ_Test/YZ_Test_1/
>   Size: 4096      	Blocks: 8          IO Block: 4096   directory
> Device: 811h/2065d	Inode: 177602572   Links: 5
> Access: (0775/drwxrwxr-x)  Uid: (  999/ minknow)   Gid: (  998/ minknow)
> Access: 2021-08-03 13:47:16.357777677 +0300
> Modify: 2021-08-03 13:37:31.387586246 +0300
> Change: 2021-08-03 13:37:31.387586246 +0300
>  Birth: -
> (readfish) (base) zhany0s@kw60889:~/Yingzi_software$ groups
> g-zhany0s sudo noor-users rc-stemcellrlab
> ```

Hi, would appreciate if someone can help with this. I tried several "group" names but it didn't work.

**Comment by YingziZhang-github** [comment]
> Have you tried installing the issue153 code above? Which branch are you on?

Hi, after I installed issue153, everything went fine. Thank you!
