### ISSUE TITLE
"failed to pick subchannel, failed to connect to all adress"

### ISSUE THREAD

**Issue by Oufra** [LooseLab/readfish#156]
Hello,

I'm having issues with step 5 of the "Testing basecalling and mapping." section of the read me.

This is the output i get when running the command as per instructed :

```
2021-07-01 15:01:40,914 ru.ru_gen batch_size=512
2021-07-01 15:01:40,914 ru.ru_gen cache_size=512
2021-07-01 15:01:40,914 ru.ru_gen channels=[1, 512]
2021-07-01 15:01:40,914 ru.ru_gen chunk_log=None
2021-07-01 15:01:40,914 ru.ru_gen command=targets
2021-07-01 15:01:40,914 ru.ru_gen device=MN24018
2021-07-01 15:01:40,914 ru.ru_gen dry_run=False
2021-07-01 15:01:40,914 ru.ru_gen experiment_name=RU Test basecall and map
2021-07-01 15:01:40,914 ru.ru_gen func=<function run at 0x7f2885a311e0>
2021-07-01 15:01:40,914 ru.ru_gen host=127.0.0.1
2021-07-01 15:01:40,914 ru.ru_gen log_file=ru_test.log
2021-07-01 15:01:40,914 ru.ru_gen log_format=%(asctime)s %(name)s %(message)s
2021-07-01 15:01:40,914 ru.ru_gen log_level=info
2021-07-01 15:01:40,914 ru.ru_gen paf_log=None
2021-07-01 15:01:40,914 ru.ru_gen port=9501
2021-07-01 15:01:40,915 ru.ru_gen run_time=172800
2021-07-01 15:01:40,915 ru.ru_gen throttle=0.4
2021-07-01 15:01:40,915 ru.ru_gen toml=data/TOML/adaptive_dragon.toml
2021-07-01 15:01:40,915 ru.ru_gen unblock_duration=0.1
2021-07-01 15:01:40,915 ru.ru_gen workers=1
2021-07-01 15:01:40,933 ru.ru_gen Initialising minimap2 mapper
2021-07-01 15:01:49,046 ru.ru_gen Mapper initialised
Traceback (most recent call last):
  File "/home/minion/projets/adaptive_sampling/bin/readfish/bin/readfish", line 11, in <module>
    sys.exit(main())
  File "/home/minion/projets/adaptive_sampling/bin/readfish/lib/python3.6/site-packages/ru/cli.py", line 42, in main
    args.func(parser, args)
  File "/home/minion/projets/adaptive_sampling/bin/readfish/lib/python3.6/site-packages/ru/ru_gen.py", line 456, in run
    position = get_device(args.device, host=args.host)
  File "/home/minion/projets/adaptive_sampling/bin/readfish/lib/python3.6/site-packages/ru/utils.py", line 758, in get_device
    manager = Manager(host=host, port=port, use_tls=use_tls)
  File "/home/minion/projets/adaptive_sampling/bin/readfish/lib/python3.6/site-packages/minknow_api/manager.py", line 108, in __init__
    minknow_api.manager_service.GetVersionInfoRequest()
  File "/home/minion/projets/adaptive_sampling/bin/readfish/lib/python3.6/site-packages/grpc/_channel.py", line 946, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/home/minion/projets/adaptive_sampling/bin/readfish/lib/python3.6/site-packages/grpc/_channel.py", line 849, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1625144509.065175407","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3009,"referenced_errors":[{"created":"@1625144509.065173716","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":398,"grpc_status":14}]}"
>
```
The TOML validation step went smoothly.

I'm running readfish 0.0.6, minion-nc 21.06.0, guppy 4.3.4.

I have to admit that I have a hard time making sense of the error message.

Thanks !

**Comment by alexomics** [comment]
This looks like a problem with connecting to the MinKNOW gRPC, with your readfish environment activated could you check your `minknow-api` version?

```
pip show minknow-api
```

**Comment by Oufra** [comment]
Thank you for responding so quickly.

Here's what i get :

```
Name: minknow-api
Version: 4.2.4
Summary: MinKNOW RPC API bindings
Home-page: UNKNOWN
Author: Oxford Nanopore Technologies Ltd
Author-email: info@nanoporetech.com
License: UNKNOWN
Location: /home/minion/.local/lib/python3.6/site-packages
Requires: numpy, protobuf, grpcio, packaging
```

**Comment by alexomics** [comment]
It seems like MinKNOW is not running it's server, the server isn't accessible, or not on it's standard port. 

How was MinKNOW installed? Does running `systemctl status minknow` show as active/running?

**Comment by Oufra** [comment]
It seemss to be indeed runin : 
```
● minknow.service - MinKNOW Instrument Software for MinION (daemon)
   Loaded: loaded (/lib/systemd/system/minknow.service; enabled; vendor preset: enabled)
   Active: active (running) since Wed 2021-06-30 19:11:54 CEST; 1 day 17h ago
 Main PID: 1766 (mk_manager_svc)
    Tasks: 185 (limit: 4915)
   CGroup: /system.slice/minknow.service
           ├─1766 /opt/ont/minknow/bin/mk_manager_svc
           ├─1774 /opt/ont/minknow/bin/crashpad_handler --database=/var/lib/minknow/data/core-dump-db --metrics-dir=/var/lib/minknow/data/core-dump-db --url=https://submit.backtrace.io/nanoporetech/6e3c49
           ├─1811 /opt/ont/minknow/bin/grpcwebproxy --server_tls_cert_file=/opt/ont/minknow/conf/rpc-certs/localhost.crt --server_tls_key_file=/opt/ont/minknow/conf/rpc-certs/localhost.key --backend_addr=
           ├─1812 /opt/ont/minknow/bin/basecall_manager --guppy-address 5555 --conf /opt/ont/minknow/conf --insecure 127.0.0.1:9504 --secure 127.0.0.1:0 --queued-command-count 1
           ├─1821 /opt/ont/minknow/bin/crashpad_handler --database=/var/lib/minknow/data/core-dump-db --metrics-dir=/var/lib/minknow/data/core-dump-db --url=https://submit.backtrace.io/nanoporetech/6e3c49
           ├─1851 /opt/ont/minknow/bin/grpcwebproxy --server_tls_cert_file=/opt/ont/minknow/conf/rpc-certs/localhost.crt --server_tls_key_file=/opt/ont/minknow/conf/rpc-certs/localhost.key --backend_addr=
           ├─2212 /opt/ont/minknow/bin/control_server --config /tmp/minknow_c9926cb2-cbef-4707-afeb-fd635847434a/conf-MN24018 --queued-command-count 1
           ├─2215 /opt/ont/minknow/bin/crashpad_handler --database=/var/lib/minknow/data/core-dump-db --metrics-dir=/var/lib/minknow/data/core-dump-db --url=https://submit.backtrace.io/nanoporetech/6e3c49
           ├─2253 /opt/ont/minknow/bin/analyser --config /tmp/minknow_c9926cb2-cbef-4707-afeb-fd635847434a/conf-MN24018
           ├─2254 /opt/ont/minknow/bin/grpcwebproxy --server_tls_cert_file=/opt/ont/minknow/conf/rpc-certs/localhost.crt --server_tls_key_file=/opt/ont/minknow/conf/rpc-certs/localhost.key --backend_addr=
           ├─2263 /opt/ont/minknow/bin/crashpad_handler --database=/var/lib/minknow/data/core-dump-db --metrics-dir=/var/lib/minknow/data/core-dump-db --url=https://submit.backtrace.io/nanoporetech/6e3c49
           └─4564 /usr/bin/guppy_basecall_server --config dna_r9.4.1_450bps_fast.cfg --port 5555 --log_path /var/log/minknow/guppy --ipc_threads 4 --max_queued_reads 5000 --chunks_per_runner 256 --num_cal

juin 30 19:11:39 posteminion systemd[1]: Starting MinKNOW Instrument Software for MinION (daemon)...
juin 30 19:11:54 posteminion systemd[1]: Started MinKNOW Instrument Software for MinION (daemon).
juin 30 19:12:25 posteminion minknow[1766]: libusb: error [get_usbfs_fd] libusb couldn't open USB device /dev/bus/usb/001/006, errno=13
juin 30 19:12:25 posteminion minknow[1766]: libusb: error [get_usbfs_fd] libusb requires write access to USB device nodes
juin 30 19:12:30 posteminion minknow[1766]: libusb: error [get_usbfs_fd] libusb couldn't open USB device /dev/bus/usb/002/004, errno=13
juin 30 19:12:30 posteminion minknow[1766]: libusb: error [get_usbfs_fd] libusb requires write access to USB device nodes
juil. 01 15:30:00 posteminion minknow[1766]: libusb: error [get_usbfs_fd] libusb couldn't open USB device /dev/bus/usb/001/007, errno=13
juil. 01 15:30:00 posteminion minknow[1766]: libusb: error [get_usbfs_fd] libusb requires write access to USB device nodes
juil. 01 15:30:05 posteminion minknow[1766]: libusb: error [get_usbfs_fd] libusb couldn't open USB device /dev/bus/usb/002/006, errno=13
juil. 01 15:30:05 posteminion minknow[1766]: libusb: error [get_usbfs_fd] libusb requires write access to USB device nodes
~
~
```

My install may be a little uncommon, let me explain :

I installed MinKNOW throught apt-get after adding the ONT repo (version 21.06.0).
I couldn't enable GPU basecalling on MinKNOW using Guppy 5.0.11 as per the instruction on ONT website . Guppy_basecall_server was not showing on nvidia-smi). I also tried the method shown [here](https://github.com/sirselim/jetson_nanopore_sequencing/blob/main/live_basecalling.md.), but to no avail. Command line Guppy works perfectly well.

Out of desperation, i downgraded to Guppy 4.3.4, and it seemed to be working at first, i.e. guppy processses do show in nvidia-smi. But basecalling and MinKNOW adaptive sampling analysis actually leads to an error for the former, and just plain not work for the second (it's just sequencing everything) -- but this might be a little off topic.

**Comment by Oufra** [comment]
Update : i finally managed to get MinKNOW 21.06.0 (Minknow core 4.3.4) and Guppy 5.0.11 to play nice together. Both through apt-get with the ONT repo.

I still get the error described in my first message though.

It could be completely unrelated, but, as our lab is located in a hospital with strict IT security protocol, we've been (begrudgingly) allowed by ONT to do offline sequencing. So "our" MinKNOW has a few, minor tweaks that allows that. Our machine is connected to the internet through the hospital network, but behind extremely restrictive measures.

**Comment by mattloose** [comment]
Closing due to inactivity - feel free to reopen.

**Comment by rainwala** [comment]
we have the same error
