### ISSUE TITLE
PermissionError: Permission denied for unblocked_read_ids.txt

### ISSUE THREAD

**Issue by YingziZhang-github** [LooseLab/readfish#158]
Hi there,
I was testing unblock response using the command `readfish unblock-all --device MN32433 --experiment-name "YZ_Test"` and I got this error. Would you help, please? Thank you very much.
```
INFO 2021-08-01 23:27:51,493 Manager /home/zhany0s/Yingzi_software/readfish/bin/readfish unblock-all --device MN32433 --experiment-name YZ_Test
2021-08-01 23:27:51,493 Manager /home/zhany0s/Yingzi_software/readfish/bin/readfish unblock-all --device MN32433 --experiment-name YZ_Test
INFO 2021-08-01 23:27:51,493 Manager batch_size=512
2021-08-01 23:27:51,493 Manager batch_size=512
INFO 2021-08-01 23:27:51,493 Manager cache_size=512
2021-08-01 23:27:51,493 Manager cache_size=512
INFO 2021-08-01 23:27:51,493 Manager channels=[1, 512]
2021-08-01 23:27:51,493 Manager channels=[1, 512]
INFO 2021-08-01 23:27:51,493 Manager command=unblock-all
2021-08-01 23:27:51,493 Manager command=unblock-all
INFO 2021-08-01 23:27:51,493 Manager device=MN32433
2021-08-01 23:27:51,493 Manager device=MN32433
INFO 2021-08-01 23:27:51,493 Manager dry_run=False
2021-08-01 23:27:51,493 Manager dry_run=False
INFO 2021-08-01 23:27:51,493 Manager experiment_name=YZ_Test
2021-08-01 23:27:51,493 Manager experiment_name=YZ_Test
INFO 2021-08-01 23:27:51,493 Manager func=<function run at 0x14c5a757d5e0>
2021-08-01 23:27:51,493 Manager func=<function run at 0x14c5a757d5e0>
INFO 2021-08-01 23:27:51,493 Manager host=127.0.0.1
2021-08-01 23:27:51,493 Manager host=127.0.0.1
INFO 2021-08-01 23:27:51,493 Manager log_file=None
2021-08-01 23:27:51,493 Manager log_file=None
INFO 2021-08-01 23:27:51,494 Manager log_format=%(asctime)s %(name)s %(message)s
2021-08-01 23:27:51,494 Manager log_format=%(asctime)s %(name)s %(message)s
INFO 2021-08-01 23:27:51,494 Manager log_level=info
2021-08-01 23:27:51,494 Manager log_level=info
INFO 2021-08-01 23:27:51,494 Manager port=9501
2021-08-01 23:27:51,494 Manager port=9501
INFO 2021-08-01 23:27:51,494 Manager run_time=172800
2021-08-01 23:27:51,494 Manager run_time=172800
INFO 2021-08-01 23:27:51,494 Manager throttle=0.4
2021-08-01 23:27:51,494 Manager throttle=0.4
INFO 2021-08-01 23:27:51,494 Manager unblock_duration=0.1
2021-08-01 23:27:51,494 Manager unblock_duration=0.1
INFO 2021-08-01 23:27:51,494 Manager workers=1
2021-08-01 23:27:51,494 Manager workers=1
INFO 2021-08-01 23:27:51,501 ReadUntil Got rpc connection.
2021-08-01 23:27:51,501 ReadUntil Got rpc connection.
INFO 2021-08-01 23:27:51,507 ReadUntil Creating single chunk client with AccumulatingCache data queue filtering to adapter and strand read chunks.
2021-08-01 23:27:51,507 ReadUntil Creating single chunk client with AccumulatingCache data queue filtering to adapter and strand read chunks.
DEBUG 2021-08-01 23:27:51,507 ReadUntil Strand-like classes are {65, 83}.
Traceback (most recent call last):
  File "/home/zhany0s/Yingzi_software/readfish/bin/readfish", line 11, in <module>
    load_entry_point('readfish==0.0.6', 'console_scripts', 'readfish')()
  File "/home/zhany0s/Yingzi_software/readfish/lib/python3.8/site-packages/ru/cli.py", line 42, in main
    args.func(parser, args)
  File "/home/zhany0s/Yingzi_software/readfish/lib/python3.8/site-packages/ru/unblock_all.py", line 129, in run
    read_until_client = RUClient(
  File "/home/zhany0s/Yingzi_software/readfish/lib/python3.8/site-packages/ru/read_until_client.py", line 42, in __init__
    self.file_handler = logging.FileHandler(
  File "/home/zhany0s/anaconda3/lib/python3.8/logging/__init__.py", line 1143, in __init__
    StreamHandler.__init__(self, self._open())
  File "/home/zhany0s/anaconda3/lib/python3.8/logging/__init__.py", line 1172, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
PermissionError: [Errno 13] Permission denied: '/nanopore/minknow/data/YZ_Test/YZ_Test_1/20210801_2322_MN32433_FAP69493_8b206807/unblocked_read_ids.txt'
```

**Comment by mattloose** [comment]
Please have a look at #153 where this is reported as a bug with a solution.
