### ISSUE TITLE
error when installing guppy_6 branch on Ubuntu 18.04 LTS, guppy_basecall_server version 5.1.12

### ISSUE THREAD

**Issue by rainwala** [LooseLab/readfish#180]
Hello, I'm trying to install the guppy_6 branch on Ubuntu 18.04 LTS, with guppy_basecall_server version 5.1.12 . I ran the installation commands as per the github page:

```
python3 -m venv readfish
. ./readfish/bin/activate
pip install --upgrade pip

# Install our ReadFish Software
pip install git+https://github.com/nanoporetech/read_until_api@v3.0.0
pip install git+https://github.com/LooseLab/readfish@dev

# Install ont_pyguppy_client_lib that matches your guppy server version. E.G.
pip install ont_pyguppy_client_lib==5.1.12
```

Then I got the following error when I tried running `readfish -h`:

```
Traceback (most recent call last):
  File "/home/aawan/readfish/bin/readfish", line 11, in <module>
    load_entry_point('readfish==0.0.8a1', 'console_scripts', 'readfish')()
  File "/home/aawan/readfish/lib/python3.6/site-packages/ru/cli.py", line 35, in main
    _module = importlib.import_module("ru.{}".format(module))
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/aawan/readfish/lib/python3.6/site-packages/ru/ru_gen.py", line 19, in <module>
    from ru.arguments import BASE_ARGS
  File "/home/aawan/readfish/lib/python3.6/site-packages/ru/arguments.py", line 7, in <module>
    from ru.utils import nice_join
  File "/home/aawan/readfish/lib/python3.6/site-packages/ru/utils.py", line 735, in <module>
    def get_barcode_kits(address, timeout=10000):
  File "/usr/lib/python3.6/functools.py", line 477, in lru_cache
    raise TypeError('Expected maxsize to be an integer or None')
TypeError: Expected maxsize to be an integer or None

```

Previously I installed the readfish from the main branch on this same computer with the same version of guppy_basecall_server without any problems.

**Comment by alexomics** [comment]
It looks like you installed the `dev` branch not the guppy 6 branch.

Try:
```bash
pip install git+https://github.com/LooseLab/readfish@guppy_6
```

**Comment by rainwala** [comment]
Ah OK that worked, thanks! The installation instructions on the guppy_6 branch currently use the dev branch -- could you please update the installation instructions on the README for the guppy_6 branch?

**Comment by alexomics** [comment]
Ah, sorry about that. I'm currently in the process of merging everything back into a stable `dev` branch.
