### ISSUE TITLE
error on step 5 of "Testing basecalling and mapping." from bulkfile simulation 

### ISSUE THREAD

**Issue by rainwala** [LooseLab/readfish#188]
At step 5 of the  "Testing basecalling and mapping."  section from https://github.com/LooseLab/readfish/tree/guppy_6, I get the following error:

```
readfish targets --device MN22761               --experiment-name "RU Test basecall and map"               --toml /home/aawan/human_chr_selection.toml               --log-file ru_test.log
2022-03-29 12:36:05,863 ru.ru_gen /home/aawan/readfish/bin/readfish targets --device MN22761 --experiment-name RU Test basecall and map --toml /home/aawan/human_chr_selection.toml --log-file ru_test.log
2022-03-29 12:36:05,863 ru.ru_gen batch_size=512
2022-03-29 12:36:05,878 ru.ru_gen cache_size=512
2022-03-29 12:36:05,878 ru.ru_gen channels=[1, 512]
2022-03-29 12:36:05,878 ru.ru_gen chunk_log=None
2022-03-29 12:36:05,878 ru.ru_gen command=targets
2022-03-29 12:36:05,878 ru.ru_gen device=MN22761
2022-03-29 12:36:05,878 ru.ru_gen dry_run=False
2022-03-29 12:36:05,878 ru.ru_gen experiment_name=RU Test basecall and map
2022-03-29 12:36:05,878 ru.ru_gen func=<function run at 0x7f775e597d90>
2022-03-29 12:36:05,878 ru.ru_gen host=127.0.0.1
2022-03-29 12:36:05,879 ru.ru_gen log_file=ru_test.log
2022-03-29 12:36:05,879 ru.ru_gen log_format=%(asctime)s %(name)s %(message)s
2022-03-29 12:36:05,879 ru.ru_gen log_level=info
2022-03-29 12:36:05,879 ru.ru_gen paf_log=None
2022-03-29 12:36:05,879 ru.ru_gen port=9501
2022-03-29 12:36:05,879 ru.ru_gen run_time=172800
2022-03-29 12:36:05,879 ru.ru_gen throttle=0.4
2022-03-29 12:36:05,879 ru.ru_gen toml=/home/aawan/human_chr_selection.toml
2022-03-29 12:36:05,879 ru.ru_gen unblock_duration=0.1
2022-03-29 12:36:05,879 ru.ru_gen workers=1
2022-03-29 12:36:05,887 ru.ru_gen Initialising minimap2 mapper
2022-03-29 12:36:12,835 ru.ru_gen Mapper initialised
Traceback (most recent call last):
  File "/home/aawan/readfish/bin/readfish", line 11, in <module>
    load_entry_point('readfish==0.0.9a1', 'console_scripts', 'readfish')()
  File "/home/aawan/readfish/lib/python3.6/site-packages/ru/cli.py", line 43, in main
    args.func(parser, args)
  File "/home/aawan/readfish/lib/python3.6/site-packages/ru/ru_gen.py", line 462, in run
    cache_type=AccumulatingCache,
  File "/home/aawan/readfish/lib/python3.6/site-packages/ru/read_until_client.py", line 27, in __init__
    self.connection.protocol.get_current_protocol_run().output_path
  File "/home/aawan/readfish/lib/python3.6/site-packages/minknow_api/protocol_service.py", line 562, in get_current_protocol_run
    "minknow_api.protocol.ProtocolService")
  File "/home/aawan/readfish/lib/python3.6/site-packages/minknow_api/protocol_service.py", line 96, in run_with_retry
    result = MessageWrapper(method(message, timeout=timeout), unwraps=unwraps)
  File "/home/aawan/readfish/lib/python3.6/site-packages/grpc/_channel.py", line 946, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/home/aawan/readfish/lib/python3.6/site-packages/grpc/_channel.py", line 849, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.FAILED_PRECONDITION
        details = "No protocol running"
        debug_error_string = "{"created":"@1648553772.846388073","description":"Error received from peer ipv4:127.0.0.1:8003","file":"src/core/lib/surface/call.cc","file_line":903,"grpc_message":"No protocol running","grpc_status":9}"
>

```

**Comment by rainwala** [comment]
could the libusb errors be causing the selective sequencing test failure?

**Comment by rainwala** [comment]
Also:
```
pip show minknow-api
Name: minknow-api
Version: 4.5.0
Summary: MinKNOW RPC API bindings
Home-page: https://github.com/nanoporetech/minknow_api
Author: Oxford Nanopore Technologies Ltd
Author-email: info@nanoporetech.com
License: UNKNOWN
Location: /home/aawan/readfish/lib/python3.6/site-packages
Requires: grpcio, numpy, packaging, protobuf, pyrfc3339
Required-by: read-until, readfish
```

**Comment by rainwala** [comment]
I am trying the fix suggested in issue 187. Will update this when I find out if it works.

**Comment by mattloose** [comment]
From your first issue we can see the following message:

```
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.FAILED_PRECONDITION
        details = "No protocol running"
        debug_error_string = "{"created":"@1648553772.846388073","description":"Error received from peer ipv4:127.0.0.1:8003","file":"src/core/lib/surface/call.cc","file_line":903,"grpc_message":"No protocol running","grpc_status":9}"
```

This suggests that the device wasn't sequencing when you tried to connect to it. You should already have the run in progress. 

Also we will shortly post another set (!) of conda instructions for install.

**Comment by rainwala** [comment]
Ah OK, the instructions weren't clear about that, I'll have the playback running next time I try.

**Comment by rainwala** [comment]
I was having the exact same error as the original one experienced by the OP in #187 , using MiNION 22.03.5

I just deleted readfish and re-installed as per your latest instructions using the yml file above iwth MinKNOW api set to 5.0.0. However, even though the codepython -c "from minknow_api.manager import Manager as M; mg=M('localhost', 9502); print([pos.name for pos in mg.flow_cell_positions()])now gives me the device IDS, I now have a different problem.

Now in the MinKNOW GUI System messages I get the following message when I reload scripts:
sequencing_MIN106_DNA_playback.toml: Cannot be parsed correctly - Bream major version Incompatibility. Check the file.

**Comment by rainwala** [comment]
Looking at the output of readfish targets, and comparing it to the edited human_chr_selection.toml file, I see that the hosts seem to be inconsistent. In the toml file, I have 
`host = "ipc:///tmp/.guppy"`

But in the readfish target command output it says:
`2022-03-29 17:24:38,865 ru.ru_gen host=127.0.0.1`

**Comment by alexomics** [comment]
The first (`ipc:...`) is the guppy host address, the second is the MinKNOW address. 

The error that you're seeing when running `sudo readfish targets` is that your shell cannot find the readfish scripts. You may need to run, with the environment activated:

```bash
$ which readfish
/some/path/to/readfish
```

Then use the output from `which` as the path to the readfish scripts:

```bash
$ /some/path/to/readfish targets
```

**Comment by rainwala** [comment]
Thanks @alexomics . I had thought it was a permissions thing, but it turns out it was an absolute path thing, as you suggested above. Using the full path the sudo command works, and now it seems like the selective sequencing is giving me the expected output on the command line, for example:

`2022-03-30 08:59:16,936 ru.ru_gen 111R/0.89562s`

**Comment by rainwala** [comment]
The selective sequencing simulation works as expected now, thank you!
