### ISSUE TITLE
TLS error when running unblock-all

### ISSUE THREAD

**Issue by melkramer** [LooseLab/readfish#204]
Hello,

We are getting an error when trying to test unblocking as per the protocol instructions.  The process seems to start running but always errors with the same message (I've tried changing the host IP, the port, and re-creating the conda environment).  Could you please advise on what the issue might be?

Thank you,
Melissa

$ readfish unblock-all --device X1 --experiment-name "Testing ReadFish Unblock All"

2022-06-29 16:41:51,196 Manager /data/.miniconda/envs/readfish/bin/readfish unblock-all --device X1 --experiment-name Testing ReadFish Unblock All
INFO 2022-06-29 16:41:51,196 Manager batch_size=512
2022-06-29 16:41:51,196 Manager batch_size=512
INFO 2022-06-29 16:41:51,196 Manager cache_size=512
2022-06-29 16:41:51,196 Manager cache_size=512
INFO 2022-06-29 16:41:51,196 Manager channels=[1, 512]
2022-06-29 16:41:51,196 Manager channels=[1, 512]
INFO 2022-06-29 16:41:51,196 Manager command=unblock-all
2022-06-29 16:41:51,196 Manager command=unblock-all
INFO 2022-06-29 16:41:51,196 Manager device=X1
2022-06-29 16:41:51,196 Manager device=X1
INFO 2022-06-29 16:41:51,196 Manager dry_run=False
2022-06-29 16:41:51,196 Manager dry_run=False
INFO 2022-06-29 16:41:51,196 Manager experiment_name=Testing ReadFish Unblock All
2022-06-29 16:41:51,196 Manager experiment_name=Testing ReadFish Unblock All
INFO 2022-06-29 16:41:51,196 Manager func=<function run at 0x7fe6413efdc0>
2022-06-29 16:41:51,196 Manager func=<function run at 0x7fe6413efdc0>
INFO 2022-06-29 16:41:51,196 Manager host=127.0.0.1
2022-06-29 16:41:51,196 Manager host=127.0.0.1
INFO 2022-06-29 16:41:51,196 Manager log_file=None
2022-06-29 16:41:51,196 Manager log_file=None
INFO 2022-06-29 16:41:51,196 Manager log_format=%(asctime)s %(name)s %(message)s
2022-06-29 16:41:51,196 Manager log_format=%(asctime)s %(name)s %(message)s
INFO 2022-06-29 16:41:51,196 Manager log_level=info
2022-06-29 16:41:51,196 Manager log_level=info
INFO 2022-06-29 16:41:51,196 Manager port=9501
2022-06-29 16:41:51,196 Manager port=9501
INFO 2022-06-29 16:41:51,196 Manager run_time=172800
2022-06-29 16:41:51,196 Manager run_time=172800
INFO 2022-06-29 16:41:51,196 Manager throttle=0.4
2022-06-29 16:41:51,196 Manager throttle=0.4
INFO 2022-06-29 16:41:51,196 Manager unblock_duration=0.1
2022-06-29 16:41:51,196 Manager unblock_duration=0.1
INFO 2022-06-29 16:41:51,196 Manager workers=1
2022-06-29 16:41:51,196 Manager workers=1
Traceback (most recent call last):
  File "/data/.miniconda/envs/readfish/bin/readfish", line 8, in <module>
    sys.exit(main())
  File "/data/.miniconda/envs/readfish/lib/python3.8/site-packages/ru/cli.py", line 43, in main
    args.func(parser, args)
  File "/data/.miniconda/envs/readfish/lib/python3.8/site-packages/ru/unblock_all.py", line 127, in run
    position = get_device(args.device)
  File "/data/.miniconda/envs/readfish/lib/python3.8/site-packages/ru/utils.py", line 918, in get_device
    manager = Manager(host=host, port=port, use_tls=use_tls)
TypeError: __init__() got an unexpected keyword argument 'use_tls'

**Comment by alexomics** [comment]
Hi Melissa, Are you running using MinKNOW v5? I think that you need to use the issue187 branch.

Your conda environment should look something like this, don't forget to set your Guppy version: 

```yaml
name: readfish
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - pip
  - pip:
    - git+https://github.com/nanoporetech/read_until_api@v3.0.0
    - git+https://github.com/LooseLab/readfish@issue187
    - ont-pyguppy-client-lib==6.0.6
```

Please let me know if you run into any other issues.

**Comment by melkramer** [comment]
Hi Matt,


Just wanted to follow up on this to see if you knew why the software hangs on basecalling?


Thanks very much,
Melissa


________________________________
