### ISSUE TITLE
"MinKNOW not found on this computer"

### ISSUE THREAD

**Issue by merfre** [LooseLab/readfish#211]
Hello,

I just reinstalled ReadFish on my machine (Ubuntu 20.04) using the instructions on the README and when I tried to test it on a playback run (which had already begun sequencing) got this output:

`sudo /home/merfre/readfish/bin/readfish targets --device MN17166 --experiment-name "RU Test basecall and map" --toml /home/merfre/human_chr_selection.toml --log-file ru_adap_gpu_test.log`

2022-09-06 14:33:37,252 Manager /home/merfre/readfish/bin/readfish targets --device MN17166 --experiment-name RU Test basecall and map --toml /home/merfre/human_chr_selection.toml --log-file ru_adap_gpu_test.log
2022-09-06 14:33:37,252 Manager batch_size=512
2022-09-06 14:33:37,252 Manager cache_size=512
2022-09-06 14:33:37,252 Manager channels=[1, 512]
2022-09-06 14:33:37,252 Manager chunk_log=chunk_log.log
2022-09-06 14:33:37,252 Manager command=targets
2022-09-06 14:33:37,252 Manager device=MN17166
2022-09-06 14:33:37,252 Manager dry_run=False
2022-09-06 14:33:37,252 Manager experiment_name=RU Test basecall and map
2022-09-06 14:33:37,252 Manager func=<function run at 0x7fad54089a60>
2022-09-06 14:33:37,252 Manager host=127.0.0.1
2022-09-06 14:33:37,253 Manager log_file=ru_adap_gpu_test.log
2022-09-06 14:33:37,253 Manager log_format=%(asctime)s %(name)s %(message)s
2022-09-06 14:33:37,253 Manager log_level=info
2022-09-06 14:33:37,253 Manager paf_log=paflog.log
2022-09-06 14:33:37,253 Manager port=9501
2022-09-06 14:33:37,253 Manager read_cache=AccumulatingCache
2022-09-06 14:33:37,253 Manager run_time=172800
2022-09-06 14:33:37,253 Manager throttle=0.1
2022-09-06 14:33:37,253 Manager toml=/home/merfre/human_chr_selection.toml
2022-09-06 14:33:37,253 Manager unblock_duration=0.1
2022-09-06 14:33:37,253 Manager workers=1
2022-09-06 14:33:37,256 Manager Initialising minimap2 mapper
2022-09-06 14:33:41,644 Manager Mapper initialised
2022-09-06 14:33:41,644 read_until_api_v2.main Client type: many chunk
2022-09-06 14:33:41,644 read_until_api_v2.main Cache type: AccumulatingCache
2022-09-06 14:33:41,644 read_until_api_v2.main Filter for classes: adapter and strand
2022-09-06 14:33:41,644 read_until_api_v2.main Creating rpc connection for device MN17166.
Traceback (most recent call last):
  File "/home/merfre/readfish/bin/readfish", line 11, in <module>
    load_entry_point('readfish==0.0.4', 'console_scripts', 'readfish')()
  File "/home/merfre/readfish/lib/python3.8/site-packages/ru/cli.py", line 33, in main
    args.func(parser, args)
  File "/home/merfre/readfish/lib/python3.8/site-packages/ru/ru_gen.py", line 493, in run
    read_until_client = read_until.ReadUntilClient(
  File "/home/merfre/readfish/lib/python3.8/site-packages/read_until_api_v2/main.py", line 240, in __init__
    self.connection, self.message_port = get_rpc_connection(
  File "/home/merfre/readfish/lib/python3.8/site-packages/read_until_api_v2/load_minknow_rpc.py", line 163, in get_rpc_connection
    load_rpc(reload)
  File "/home/merfre/readfish/lib/python3.8/site-packages/read_until_api_v2/load_minknow_rpc.py", line 139, in load_rpc
    raise ValueError("MinKNOW not found on this computer")
ValueError: MinKNOW not found on this computer

This is my config file:

```
[caller_settings]
config_name = "dna_r9.4.1_450bps_fast.cfg"
host = "ipc:///tmp/.guppy"
port = 5557

[conditions]
reference = "/home/merfre/human_reference.mmi"

[conditions.0]
name = "select_chr_21_22"
control = false
min_chunks = 0
max_chunks = inf
targets = ["CM000683.2", "CM000684.2"]
single_on = "stop_receiving"
multi_on = "stop_receiving"
single_off = "unblock"
multi_off = "unblock"
no_seq = "proceed"
no_map = "proceed"
```

This is how I started my basecalling server:

`sudo guppy_basecall_server --log_path guppy.log --config dna_r9.4.1_450bps_fast.cfg --port /tmp/.guppy/5557 --device cuda:0 --gpu_runners_per_device 8 --num_callers 4 --chunks_per_runner 1024 --chunk_size 1000`

ONT Guppy basecall server software version 6.1.1+1f6bfa7f8, client-server API version 11.0.0, minimap2 version 2.22-r1101
log path:            guppy.log
chunk size:          1000
chunks per runner:   1024
max queued reads:    2000
num basecallers:     4
num socket threads:  2
max returned events: 50000
gpu device:          cuda:0
kernel path:         
runners per device:  8
Use of this software is permitted solely under the terms of the end user license agreement (EULA).By running, copying or accessing this software, you are demonstrating your acceptance of the EULA.
The EULA may be found in /opt/ont/guppy/bin

Config loaded:
config file:               /opt/ont/guppy/data/dna_r9.4.1_450bps_fast.cfg
model file:                /opt/ont/guppy/data/template_r9.4.1_450bps_fast.jsn
model version id           2021-05-17_dna_r9.4.1_minion_96_29d8704b
adapter scaler model file: None
Starting server on port: ipc:///tmp/.guppy/5557

The readfish conda environment was active and I also tried to run it without sudo ('readfish targets --device MN17166 --experiment-name "RU Test basecall and map" --toml /home/merfre/human_chr_selection.toml --log-file ru_adap_gpu_test.log`), but that resulted in the same error. I am using minknow 5 and guppy 6.1.1

**Comment by merfre** [comment]
Duplicate issue and will write new one related to the installation of the new readfish updates.
