### ISSUE TITLE
readfish can'tfind MinKnow (22.10.7)

### ISSUE THREAD

**Issue by rdieterich** [LooseLab/readfish#222]
I tried readfish on a GridIon with recent software updates. Installed MinKnow is version 22.10.7.

Install of readfish into a Python virtual environment worked OK. But when testing it doesn't find MinKnow:

grid@GXB03523:~$ . readfish/bin/activate
(readfish) grid@GXB03523:~$ readfish unblock-all --device X1 --experiment-name "Test2"
INFO 2022-12-20 13:51:38,796 Manager /home/grid/readfish/bin/readfish unblock-all --device X1 --experiment-name Test2
2022-12-20 13:51:38,796 Manager /home/grid/readfish/bin/readfish unblock-all --device X1 --experiment-name Test2
INFO 2022-12-20 13:51:38,796 Manager batch_size=512
2022-12-20 13:51:38,796 Manager batch_size=512
INFO 2022-12-20 13:51:38,796 Manager cache_size=512
2022-12-20 13:51:38,796 Manager cache_size=512
INFO 2022-12-20 13:51:38,796 Manager channels=[1, 512]
2022-12-20 13:51:38,796 Manager channels=[1, 512]
INFO 2022-12-20 13:51:38,796 Manager command=unblock-all
2022-12-20 13:51:38,796 Manager command=unblock-all
INFO 2022-12-20 13:51:38,796 Manager device=X1
2022-12-20 13:51:38,796 Manager device=X1
INFO 2022-12-20 13:51:38,796 Manager dry_run=False
2022-12-20 13:51:38,796 Manager dry_run=False
INFO 2022-12-20 13:51:38,796 Manager experiment_name=Test2
2022-12-20 13:51:38,796 Manager experiment_name=Test2
INFO 2022-12-20 13:51:38,796 Manager func=<function run at 0x7f0945b31a60>
2022-12-20 13:51:38,796 Manager func=<function run at 0x7f0945b31a60>
INFO 2022-12-20 13:51:38,796 Manager host=127.0.0.1
2022-12-20 13:51:38,796 Manager host=127.0.0.1
INFO 2022-12-20 13:51:38,796 Manager log_file=None
2022-12-20 13:51:38,796 Manager log_file=None
INFO 2022-12-20 13:51:38,796 Manager log_format=%(asctime)s %(name)s %(message)s
2022-12-20 13:51:38,796 Manager log_format=%(asctime)s %(name)s %(message)s
INFO 2022-12-20 13:51:38,797 Manager log_level=info
2022-12-20 13:51:38,797 Manager log_level=info
INFO 2022-12-20 13:51:38,797 Manager port=9501
2022-12-20 13:51:38,797 Manager port=9501
INFO 2022-12-20 13:51:38,797 Manager read_cache=AccumulatingCache
2022-12-20 13:51:38,797 Manager read_cache=AccumulatingCache
INFO 2022-12-20 13:51:38,797 Manager run_time=172800
2022-12-20 13:51:38,797 Manager run_time=172800
INFO 2022-12-20 13:51:38,797 Manager throttle=0.1
2022-12-20 13:51:38,797 Manager throttle=0.1
INFO 2022-12-20 13:51:38,797 Manager unblock_duration=0.1
2022-12-20 13:51:38,797 Manager unblock_duration=0.1
INFO 2022-12-20 13:51:38,797 Manager workers=1
2022-12-20 13:51:38,797 Manager workers=1
2022-12-20 13:51:38,797 read_until_api_v2.main Client type: many chunk
2022-12-20 13:51:38,797 read_until_api_v2.main Cache type: AccumulatingCache
2022-12-20 13:51:38,797 read_until_api_v2.main Filter for classes: strand and adapter
2022-12-20 13:51:38,797 read_until_api_v2.main Creating rpc connection for device X1.
Traceback (most recent call last):
  File "/home/grid/readfish/bin/readfish", line 8, in <module>
    sys.exit(main())
  File "/home/grid/readfish/lib/python3.8/site-packages/ru/cli.py", line 33, in main
    args.func(parser, args)
  File "/home/grid/readfish/lib/python3.8/site-packages/ru/unblock_all.py", line 112, in run
    read_until_client = read_until.ReadUntilClient(
  File "/home/grid/readfish/lib/python3.8/site-packages/read_until_api_v2/main.py", line 240, in __init__
    self.connection, self.message_port = get_rpc_connection(
  File "/home/grid/readfish/lib/python3.8/site-packages/read_until_api_v2/load_minknow_rpc.py", line 163, in get_rpc_connection
    load_rpc(reload)
  File "/home/grid/readfish/lib/python3.8/site-packages/read_until_api_v2/load_minknow_rpc.py", line 139, in load_rpc
    raise ValueError("MinKNOW not found on this computer")
ValueError: MinKNOW not found on this computer

Does readfish work with current MinKnow versions? Or do I miss something?

**Comment by alexomics** [comment]
It seems that you have attempted to install an old version of readfish that used our (deprecated) read until API. Please delete the environment that you have created and follow the install instructions here: https://github.com/LooseLab/readfish/blob/dev_staging/README.md

**Comment by Adoni5** [comment]
Closing as inactive
