### ISSUE TITLE
Readfish intermittently crashes during barcoded experiment

### ISSUE THREAD

**Issue by jamesemery** [LooseLab/readfish#329]
I have noticed an intermittent failure in my experiments using Readfish + Barcode-Dependent target lists that seems to trigger between 0-3 times per 72 hour sequencing experiment. Always Readfish will happily restart and usually run to completion if i re-launch from the command line and thus I can work around this failure for now but it seems like a genuine bug. These experiments all have between 3 and 7 barcodes loaded on the sequencer and I have configured each of those barcodes to target independent lists (with no region splitting at all). The exceptions always take the following form ("channel=####" varies):

```
Traceback (most recent call last):
  File "/home/prom/miniconda3/envs/readfish2/bin/readfish", line 8, in <module>
    sys.exit(main())
  File "/home/prom/miniconda3/envs/readfish2/lib/python3.10/site-packages/readfish/_cli_base.py", line 61, in main
    raise SystemExit(args.func(parser, args, extras))
  File "/home/prom/miniconda3/envs/readfish2/lib/python3.10/site-packages/readfish/entry_points/targets.py", line 537, in run
    worker.run()
  File "/home/prom/miniconda3/envs/readfish2/lib/python3.10/site-packages/readfish/entry_points/targets.py", line 392, in run
    control, condition = self.conf.get_conditions(
  File "/home/prom/miniconda3/envs/readfish2/lib/python3.10/site-packages/readfish/_config.py", line 321, in get_conditions
    raise ValueError(
ValueError: Both region (channel=2806) and barcode (None) were not found. This config is invalid!
```

MinKNOW is set to `23.03.5(focal)`. My pip-list for the environment I am running is as follows:
```Package                Version
---------------------- ------------
about-time             4.2.1
alive-progress         3.1.4
attrs                  23.1.0
cattrs                 23.1.2
click                  8.1.7
exceptiongroup         1.1.3
grapheme               0.6.0
grpcio                 1.59.0
iniconfig              2.0.0
mappy                  2.26
mappy-rs               0.0.7
minknow-api            5.7.2
more-itertools         10.1.0
numpy                  1.26.0
ont-pyguppy-client-lib 6.5.7
packaging              23.2
pip                    23.2.1
pluggy                 1.3.0
protobuf               4.24.4
pyRFC3339              1.1
pytest                 7.4.2
pytz                   2023.3.post1
readfish               2023.1.1
readfish_summarise     0.2.5
rtoml                  0.9.0
setuptools             68.2.2
tomli                  2.0.1
typing_extensions      4.8.0
wheel                  0.41.2
```
I should note, I have only noticed this exception cropping up in the past month or so after this exact installation was working without incident last December. I have not intentionally updated any of my software in that time but it is certainly possible that MinKNOW was bumped to an incorrect version somehow.

**Comment by mattloose** [comment]
Hi James,

This is a suprising problem - we can have a look at this for you - would you mind sharing your toml file with us so we can have a look to better understand?

We've never seen this issue.

Feel free to delete targets etc if you don't want those to be shared.

Matt

**Comment by mattloose** [comment]
Thanks - we'll have a look at this and get back to you.

I can't immediately see anything wrong in your toml file which is good.

**Comment by mattloose** [comment]
OK - we've discussed this here. 

We think what is happening is that dorado is occasionally returning a read with a barcoded assignment. This is unexpected by readfish and so it is failing. We can implement a workaround (and will do so) but we will also alert the dorado team. We will update here when a workaround is implemented in readfish, but hopefully the upstreamt dorado behaviour will also be fixed.

A possible workaround for now would be to add an extra region to your toml file:

```
[[regions]]
name = "no_barcode_reads"
control = false
min_chunks = 0
max_chunks = 12
targets = []
single_on = "unblock"
multi_on = "unblock"
single_off = "unblock"
multi_off = "unblock"
no_seq = "proceed"
no_map = "proceed"
```

The current bug is caused by the base caller returning a read without a barcode, but readfish is expecting all reads to have a barcode or be "unclassified" by the base caller. In this case you are getting a read with no barcode but readfish has no region to assign it too. Adding in this condition will treat the read as an unclassified read and so it will be rejected.

I have to say this suggestion is posted un tested - so please proceed with caution and we will update.
