### ISSUE TITLE
RU crashes when pyguppy returns NoneType

### ISSUE THREAD

**Issue by jbeaulaurier** [LooseLab/readfish#33]
Hello,

We had a read-until run crash recently after running successfully for ~9 hours. Sequencing proceeded as normal, but the adaptive selection ceased to operate after this point. The goal of the run was to deplete reads that align to the target reference (unblock) and allow all non-mapping reads to proceed.

Here's the contents of the toml file:

> [caller_settings]
config_name = "dna_r9.4.1_450bps_hac"
host = "127.0.0.1"
port = 5555

> [conditions]
reference = "/home/grid/git/pyguppyclient/read_until/assembly.no_eupl.combo.ont.mmi"

> [conditions.0]
name = "bac_background_depletion"
control = false
min_chunks = 0
max_chunks = inf
targets = ["combined_bac_contigs"]
single_on = "unblock"
multi_on = "unblock"
single_off = "unblock"
multi_off = "unblock"
no_seq = "proceed"
no_map = "proceed"`

And here are the last few lines of the read-until log:

>2020-03-09 21:55:17,987 DEC 9655        167     3055fd3e-a776-47be-8dd2-41cb6364ee17    298     20068   8       1       no_map  proceed
2020-03-09 21:55:17,988 DEC 9655        168     746b3d88-9c1b-4768-8495-b62daebfff5c    299     17338   4816    4       no_map  proceed
2020-03-09 21:55:17,988 DEC 9655        169     9edd601d-bbf4-4cb5-b282-c1df702abf35    5       17692   887     2       no_map  proceed
2020-03-09 21:55:17,990 ru.ru_gen 169R/5.10888s
2020-03-11 13:08:09,670 Manager Sending reset
2020-03-11 13:08:09,800 Manager EXCEPT
Traceback (most recent call last):
  File "/home/grid/git/pyguppyclient/read_until/lib/python3.7/site-packages/ru/ru_gen.py", line 397, in run_workflow
    res = result.get(3)
  File "/home/grid/miniconda3/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
  File "/home/grid/miniconda3/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/home/grid/git/pyguppyclient/read_until/lib/python3.7/site-packages/ru/ru_gen.py", line 207, in simple_analysis
    decided_reads=decided_reads,
  File "/home/grid/git/pyguppyclient/read_until/lib/python3.7/site-packages/ru/basecall.py", line 146, in map_reads_2
    for read_info, read_id, seq, seq_len, quality in calls:
  File "/home/grid/git/pyguppyclient/read_until/lib/python3.7/site-packages/ru/basecall.py", line 101, in basecall_minknow
    self.pass_read(read)
  File "/home/grid/git/pyguppyclient/read_until/lib/python3.7/site-packages/pyguppyclient/client.py", line 123, in pass_read
    ), simple=False)
  File "/home/grid/git/pyguppyclient/read_until/lib/python3.7/site-packages/pyguppyclient/client.py", line 55, in send
    return simple_response(self.recv())
  File "/home/grid/git/pyguppyclient/read_until/lib/python3.7/site-packages/pyguppyclient/ipc.py", line 101, in simple_response
    raise Exception(cls.Text().decode())
AttributeError: 'NoneType' object has no attribute 'decode'

Any guidance on what happened here? It could be that this is a pyguppy bug, but I thought I'd first run it by you read-until folks to see if you have encountered this before. I'm hesitant to simply relaunch the run without debugging as this is a precious sample.

Thanks,
John

**Comment by iiSeymour** [comment]
Hey @jbeaulaurier 

That `AttributeError` error you are seeing is a bug and I've just fixed it in https://github.com/nanoporetech/pyguppyclient/commit/45f5f65353398b5519b3ed9eb91ec348730f9172 and pushed v0.0.6 to PyPI. It will now throw an `Exception("Bad request")` it's not clear exactly why the request is problematic, I suggest ru catches the exception, logs the request and either moves on or exits cleanly.

**Comment by mattloose** [comment]
Hi @jbeaulaurier thanks for alerting us about this specific issue. Now that @iiSeymour has amended the client to throw and exception we will edit our code to log and catch the exception. Our default behaviour would be to keep the code running if it encounters the error rather than exit as our assumption is that this is a rare even (we've never seen this one before).
