### ISSUE TITLE
 Handshake failed with fatal error SSL_ERROR_SSL: error:1000007d:

### ISSUE THREAD

**Issue by adbeggs** [LooseLab/readfish#370]
Hello

Thanks in advance for looking at our query. I am trying to get Readfish working on a Gridion with attached P2 Solo. 

Getting fine through the simulation bit etc but when I try and do an unblock all I get the following below. It seems to want import of a TLS certificate but I can't see how to achieve this from the ReadFish documentation:

```
2024-08-05 14:00:03,929 readfish /data/software/condaenvs/readfish/bin/readfish unblock-all --device PS2-00952-B --experiment-name Bas
2024-08-05 14:00:03,929 readfish chemistry=<Chemistry.SIMPLEX: 'simplex'>
2024-08-05 14:00:03,929 readfish command='unblock-all'
2024-08-05 14:00:03,929 readfish debug_log=True
2024-08-05 14:00:03,929 readfish device='PS2-00952-B'
2024-08-05 14:00:03,929 readfish dry_run=False
2024-08-05 14:00:03,929 readfish experiment_name='Bastard'
2024-08-05 14:00:03,929 readfish host='127.0.0.1'
2024-08-05 14:00:03,929 readfish log_file=None
2024-08-05 14:00:03,930 readfish log_format='%(asctime)s %(name)s %(message)s'
2024-08-05 14:00:03,930 readfish log_level='info'
2024-08-05 14:00:03,930 readfish max_unblock_read_length_seconds=5
2024-08-05 14:00:03,930 readfish port=None
2024-08-05 14:00:03,930 readfish throttle=0.4
2024-08-05 14:00:03,930 readfish unblock_duration=0.1
2024-08-05 14:00:03,930 readfish wait_for_ready=120
2024-08-05 14:00:03,930 readfish Version=2024.2.0
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1722866403.952401  337256 ssl_transport_security.cc:1650] Handshake failed with fatal error SSL_ERROR_SSL: error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED.
E0000 00:00:1722866403.968253  337256 ssl_transport_security.cc:1650] Handshake failed with fatal error SSL_ERROR_SSL: error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED.
Traceback (most recent call last):
  File "/data/software/condaenvs/readfish/bin/readfish", line 8, in <module>
    sys.exit(main())
  File "/data/software/condaenvs/readfish/lib/python3.10/site-packages/readfish/_cli_base.py", line 61, in main
    raise SystemExit(args.func(parser, args, extras))
  File "/data/software/condaenvs/readfish/lib/python3.10/site-packages/readfish/entry_points/unblock_all.py", line 66, in run
    ret = targets.run(parser, args, extras)
  File "/data/software/condaenvs/readfish/lib/python3.10/site-packages/readfish/entry_points/targets.py", line 587, in run
    minknow_version = _get_minknow_version(host=args.host, port=args.port)
  File "/data/software/condaenvs/readfish/lib/python3.10/site-packages/readfish/_compatibility.py", line 58, in _get_minknow_version
    manager = Manager(host=host, port=port)
  File "/data/software/condaenvs/readfish/lib/python3.10/site-packages/minknow_api/manager.py", line 361, in __init__
    version_info = self.rpc.get_version_info()
  File "/data/software/condaenvs/readfish/lib/python3.10/site-packages/minknow_api/manager_service.py", line 478, in get_version_info
    return run_with_retry(self._stub.get_version_info,
  File "/data/software/condaenvs/readfish/lib/python3.10/site-packages/minknow_api/manager_service.py", line 101, in run_with_retry
    result = MessageWrapper(method(message, timeout=timeout), unwraps=unwraps)
  File "/data/software/condaenvs/readfish/lib/python3.10/site-packages/grpc/_channel.py", line 1181, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/data/software/condaenvs/readfish/lib/python3.10/site-packages/grpc/_channel.py", line 1006, in _end_unary_response_blocking
    raise _InactiveRpcError(state)  # pytype: disable=not-instantiable
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:9502: Ssl handshake failed (TSI_PROTOCOL_FAILURE): SSL_ERROR_SSL: error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED"
	debug_error_string = "UNKNOWN:Error received from peer  {grpc_message:"failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:9502: Ssl handshake failed (TSI_PROTOCOL_FAILURE): SSL_ERROR_SSL: error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED", grpc_status:14, created_time:"2024-08-05T14:00:03.968470271+00:00"}"

```

**Comment by mattloose** [comment]
Interesting choice of experiment name.

Are you using the latest version of minKNOW by any chance?

**Comment by mattloose** [comment]
Before you update.

I suspect that your version of MinKNOW has not had the option checked to allow "guest" logins and that you need an account to log into it remotely. A quick fix woudl be to enable guest login on the GUI.

**Comment by adbeggs** [comment]
It's currently 24.02.10, upgraded to 24.02.16, guest access has been on... still same error

**Comment by adbeggs** [comment]
Here's the output of pip list:

(/data/software/condaenvs/readfish) grid@grid0001:/data/software/condaenvs$ pip list
Package                   Version
------------------------- --------
about-time                4.2.1
alive-progress            3.1.5
attrs                     24.1.0
Bottleneck                1.3.8
cattrs                    23.2.3
click                     8.1.7
exceptiongroup            1.2.2
grapheme                  0.6.0
grpcio                    1.65.4
iniconfig                 2.0.0
llvmlite                  0.42.0
mappy                     2.28
mappy-rs                  0.0.7
minknow_api               6.0.4
more-itertools            10.3.0
numba                     0.59.1
numpy                     1.26.4
ont-pybasecall-client-lib 7.4.12
packaging                 24.1
pip                       24.2
pluggy                    1.5.0
protobuf                  4.25.4
pyRFC3339                 1.1
pytest                    8.3.2
pytz                      2024.1
readfish                  2024.2.0
readfish_summarise        0.2.6
rtoml                     0.11.0
scipy                     1.12.0
setuptools                72.1.0
tomli                     2.0.1
typing_extensions         4.12.2
wheel                     0.44.0

**Comment by mattloose** [comment]
Can you check if you can remotely access minKnow on the p2solo from a different computer via minkow itself (if that makes sense...)

**Comment by adbeggs** [comment]
Yes tried that and yes I can

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by mattloose** [comment]
You are ahead of me then – I can’t connect remotely to my P2solo on minknow 6.0

Will look into this and come back to you.



From: Andrew Beggs ***@***.***>
Date: Monday, 5 August 2024 at 15:26
To: LooseLab/readfish ***@***.***>
Cc: Matthew Loose (staff) ***@***.***>, Comment ***@***.***>
Subject: Re: [LooseLab/readfish] Handshake failed with fatal error SSL_ERROR_SSL: error:1000007d: (Issue #370)
Yes tried that and yes I can

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by mattloose** [comment]
You might want to look at:

https://github.com/LooseLab/readfish/issues/356

presuming you are on a linux machine running this then the path to the certificate is:

/opt/ont/minknow/conf/rpc-certs/ca.crt

**Comment by adbeggs** [comment]
Interesting… this seems to have made a difference

A

**Comment by mattloose** [comment]
Great!

From: Andrew Beggs ***@***.***>
Date: Monday, 5 August 2024 at 16:04
To: LooseLab/readfish ***@***.***>
Cc: Matthew Loose (staff) ***@***.***>, Comment ***@***.***>
Subject: Re: [LooseLab/readfish] Handshake failed with fatal error SSL_ERROR_SSL: error:1000007d: (Issue #370)
Interesting… this seems to have made a difference

A

**Comment by adbeggs** [comment]
More joy but then:

```
2024-08-05 15:06:57,364 readfish chemistry=<Chemistry.SIMPLEX: 'simplex'>
2024-08-05 15:06:57,364 readfish command='unblock-all'
2024-08-05 15:06:57,364 readfish debug_log=True
2024-08-05 15:06:57,364 readfish device='P2S-00952-B'
2024-08-05 15:06:57,364 readfish dry_run=False
2024-08-05 15:06:57,364 readfish experiment_name='Bastard'
2024-08-05 15:06:57,364 readfish host='127.0.0.1'
2024-08-05 15:06:57,364 readfish log_file=None
2024-08-05 15:06:57,364 readfish log_format='%(asctime)s %(name)s %(message)s'
2024-08-05 15:06:57,364 readfish log_level='info'
2024-08-05 15:06:57,364 readfish max_unblock_read_length_seconds=5
2024-08-05 15:06:57,364 readfish port=None
2024-08-05 15:06:57,364 readfish throttle=0.4
2024-08-05 15:06:57,364 readfish unblock_duration=0.1
2024-08-05 15:06:57,364 readfish wait_for_ready=120
2024-08-05 15:06:57,364 readfish Version=2024.2.0
2024-08-05 15:06:57,392 readfish.unblock-all This readfish version (2024.2.0) is tested for compatibility with MinKNOW v5.0.0 to v5.9.7.
This version of minknow is 5.9.12.
If readfish fails please try to upgrade readfish.
If there isn't a newer version of readfish and readfish is failing, please open an issue:
    https://github.com/LooseLab/readfish/issues
2024-08-05 15:06:57,427 readfish._read_until_client Protocol phase changed to PHASE_SEQUENCING
2024-08-05 15:06:57,427 readfish._read_until_client Protocol state changed to PROTOCOL_RUNNING
2024-08-05 15:06:57,429 readfish.unblock-all eJxtj1EKwjAQRP9zitADCPrvSUIIadjW0M1uzaba4xtBrAn+7b4ZhhkTPCJkJ1BKpFlOxI5Xq0zy6/qPmwxzZBJrFfkE+qqHjUbksOiaNKgUyYXbRotU6ayS34/3oorPM5T3baySGozgmH5Chi+dpganDUvsvR/YWWtVgXuP6qAG+ZEf4Jp+hzgC8tM1Ww7xBaW9au4=
2024-08-05 15:06:57,450 readfish.unblock-all Configuration description:
Region unblock all (control=False).
Region applies to section of flow cell (# = applied, . = not applied):

    ########################################################################################################################
    ########################################################################################################################
    ########################################################################################################################
    ########################################################################################################################
    ########################################################################################################################
    ########################################################################################################################
    ########################################################################################################################
    ########################################################################################################################
    ########################################################################################################################
    ########################################################################################################################
    ########################################################################################################################
    ########################################################################################################################
    ########################################################################################################################

2024-08-05 15:06:57,452 readfish.unblock-all Fetching Run Configuration
2024-08-05 15:06:57,453 readfish.unblock-all Run Configuration Received
2024-08-05 15:06:57,453 readfish.unblock-all run_id=b750e3e5-c154-4a96-a24a-5a88ff61e253
2024-08-05 15:06:57,453 readfish.unblock-all break_reads_after_seconds=1.0
2024-08-05 15:06:57,453 readfish.unblock-all sample_rate=5000
2024-08-05 15:06:57,467 readfish.unblock-all Initialising Caller
2024-08-05 15:06:57,467 readfish.unblock-all Caller initialised
2024-08-05 15:06:57,467 readfish.unblock-all Using the `no_op` Caller. No base-calling will be performed, and minimum viable results will be yielded back for each read provided.
2024-08-05 15:06:57,469 readfish.unblock-all Initialising Aligner
2024-08-05 15:06:57,469 readfish.unblock-all Aligner initialised
2024-08-05 15:06:57,472 readfish.unblock-all Starting main loop
2024-08-05 15:06:57,472 readfish.unblock-all Using the `no_op` Aligner. No alignments will be performed, and all Results will be passed through.
2024-08-05 15:06:57,475 readfish.unblock-all readfish started in PHASE_SEQUENCING. Fully sequencing first read from each channel.
Traceback (most recent call last):
  File "/data/software/condaenvs/readfish/bin/readfish", line 8, in <module>
    sys.exit(main())
  File "/data/software/condaenvs/readfish/lib/python3.10/site-packages/readfish/_cli_base.py", line 61, in main
    raise SystemExit(args.func(parser, args, extras))
  File "/data/software/condaenvs/readfish/lib/python3.10/site-packages/readfish/entry_points/unblock_all.py", line 66, in run
    ret = targets.run(parser, args, extras)
  File "/data/software/condaenvs/readfish/lib/python3.10/site-packages/readfish/entry_points/targets.py", line 653, in run
    worker.run()
  File "/data/software/condaenvs/readfish/lib/python3.10/site-packages/readfish/entry_points/targets.py", line 483, in run
    chunks = self.client.get_read_chunks(self.client.channel_count, last=True)
  File "/data/software/condaenvs/readfish/lib/python3.10/site-packages/readfish/read_until/base.py", line 349, in get_read_chunks
    data = [
  File "/data/software/condaenvs/readfish/lib/python3.10/site-packages/readfish/read_until/base.py", line 352, in <listcomp>
    if read.number > self.channel_read_latest_decision[channel]
AttributeError: number
```

**Comment by mattloose** [comment]
https://github.com/LooseLab/readfish/tree/feature/minknow6-compatibility

This will be your fix....

We were hoping it would be out now but it should work. Sorry for the hassle - it's a major minknow release!

**Comment by adbeggs** [comment]
Hi @mattloose 

Still getting the AttributeError: number error with simulation.
Using Minknow 5.9.12 not 6, have downloaded the right version of readfish for this...
The Readfish for v6 won't run (although I have installed this) as it expects Minknow 6

**Comment by mattloose** [comment]
Can you try restarting your system? 5.9.12 should be working with readfish 2024.2.0 as the issue causing the number error is minkno 6.0 specific.
