### ISSUE TITLE
readfish unblock-all Command Fails with AttributeError: number with MinKNOW v6.0.8

### ISSUE THREAD

**Issue by ahfitzpa** [LooseLab/readfish#373]
I encountered an issue when running the readfish unblock-all command. The command fails with an AttributeError, and it appears to be related to using a version of MinKNOW (v6.0.8) that may not be compatible with the current version of readfish. Below is the detailed output and traceback.

`readfish unblock-all --device "MS00000" --experiment-name "Testing readfish Unblock All"`

**Output:**
```
2024-08-15` 17:55:26,098 readfish /home/grid/miniconda3/envs/readfish/bin/readfish unblock-all --device MS00000 --experiment-name Testing readfish Unblock All
2024-08-15 17:55:26,098 readfish chemistry=<Chemistry.SIMPLEX: 'simplex'>
2024-08-15 17:55:26,098 readfish command='unblock-all'
2024-08-15 17:55:26,098 readfish debug_log=True
2024-08-15 17:55:26,098 readfish device='MS00000'
2024-08-15 17:55:26,098 readfish dry_run=False
2024-08-15 17:55:26,098 readfish experiment_name='Testing readfish Unblock All'
2024-08-15 17:55:26,098 readfish host='127.0.0.1'
2024-08-15 17:55:26,098 readfish log_file=None
2024-08-15 17:55:26,098 readfish log_format='%(asctime)s %(name)s %(message)s'
2024-08-15 17:55:26,098 readfish log_level='info'
2024-08-15 17:55:26,098 readfish max_unblock_read_length_seconds=5
2024-08-15 17:55:26,098 readfish port=None
2024-08-15 17:55:26,098 readfish throttle=0.4
2024-08-15 17:55:26,098 readfish unblock_duration=0.1
2024-08-15 17:55:26,098 readfish wait_for_ready=120
2024-08-15 17:55:26,098 readfish Version=2024.2.0
2024-08-15 17:55:26,124 readfish.unblock-all This readfish version (2024.2.0) is tested for compatibility with MinKNOW v5.0.0 to v5.9.7.
This version of minknow is 6.0.8.
If readfish fails please try to upgrade readfish.
If there isn't a newer version of readfish and readfish is failing, please open an issue:
    https://github.com/LooseLab/readfish/issues
2024-08-15 17:55:26,149 readfish._read_until_client Protocol phase changed to PHASE_SEQUENCING
2024-08-15 17:55:26,149 readfish._read_until_client Protocol state changed to PROTOCOL_RUNNING
2024-08-15 17:55:26,150 readfish.unblock-all eJxtj1EKwjAQRP9zitADCPrvSUIIadjW0M1uzaba4xtBrAn+7b4ZhhkTPCJkJ1BKpFlOxI5Xq0zy6/qPmwxzZBJrFfkE+qqHjUbksOiaNKgUyYXbRotU6ayS34/3oorPM5T3baySGozgmH5Chi+dpganDUvsvR/YWWtVgXuP6qAG+ZEf4Jp+hzgC8tM1Ww7xBaW9au4=
2024-08-15 17:55:26,154 readfish.unblock-all Configuration description:
Region unblock all (control=False).
Region applies to section of flow cell (# = applied, . = not applied):

    ################################
    ################################
    ################################
    ################################
    ################################
    ################################
    ################################
    ################################

2024-08-15 17:55:26,155 readfish.unblock-all Fetching Run Configuration
2024-08-15 17:55:26,156 readfish.unblock-all Run Configuration Received
2024-08-15 17:55:26,156 readfish.unblock-all run_id=17e42758-9633-4050-b0b7-d13dfa875ba7
2024-08-15 17:55:26,156 readfish.unblock-all break_reads_after_seconds=0.8
2024-08-15 17:55:26,156 readfish.unblock-all sample_rate=5000
2024-08-15 17:55:26,156 readfish.unblock-all Initialising Caller
2024-08-15 17:55:26,156 readfish.unblock-all Caller initialised
2024-08-15 17:55:26,156 readfish.unblock-all Using the `no_op` Caller. No base-calling will be performed, and minimum viable results will be yielded back for each read provided.
2024-08-15 17:55:26,157 readfish.unblock-all Initialising Aligner
2024-08-15 17:55:26,157 readfish.unblock-all Aligner initialised
2024-08-15 17:55:26,157 readfish.unblock-all Starting main loop
2024-08-15 17:55:26,157 readfish.unblock-all Using the `no_op` Aligner. No alignments will be performed, and all Results will be passed through.
2024-08-15 17:55:26,158 readfish.unblock-all readfish started in PHASE_SEQUENCING. Fully sequencing first read from each channel.
Traceback (most recent call last):
  File "/home/grid/miniconda3/envs/readfish/bin/readfish", line 8, in <module>
    sys.exit(main())
  File "/home/grid/miniconda3/envs/readfish/lib/python3.10/site-packages/readfish/_cli_base.py", line 61, in main
    raise SystemExit(args.func(parser, args, extras))
  File "/home/grid/miniconda3/envs/readfish/lib/python3.10/site-packages/readfish/entry_points/unblock_all.py", line 66, in run
    ret = targets.run(parser, args, extras)
  File "/home/grid/miniconda3/envs/readfish/lib/python3.10/site-packages/readfish/entry_points/targets.py", line 653, in run
    worker.run()
  File "/home/grid/miniconda3/envs/readfish/lib/python3.10/site-packages/readfish/entry_points/targets.py", line 483, in run
    chunks = self.client.get_read_chunks(self.client.channel_count, last=True)
  File "/home/grid/miniconda3/envs/readfish/lib/python3.10/site-packages/readfish/read_until/base.py", line 349, in get_read_chunks
    data = [
  File "/home/grid/miniconda3/envs/readfish/lib/python3.10/site-packages/readfish/read_until/base.py", line 352, in <listcomp>
    if read.number > self.channel_read_latest_decision[channel]
AttributeError: number
``` 

**Environment:**

    readfish version: 2024.2.0
    minknow-api version: 6.0.4
    MinKNOW version: 6.0.8
    Python version: 3.10

**Comment by ahfitzpa** [comment]
I have resolved this after looking through issue #370

`pip install git+https://github.com/LooseLab/readfish.git@feature/minknow6-compatibility
`
